### PR TITLE
Adapt to new gardener resources

### LINKED ISSUE #118: Can specify invalid volume size via Gardener dashboard
Hi colleagues, 

when creating a new cluster with Gardener 1.14.0 , I can specify a volume size of 1Gi which leads to the following error: 

"Shoot.garden.sapcloud.io "jasonktest" is invalid: spec.cloud.aws.workers[0].volumeSize: Invalid value: "1Gi": volume size must be at least 20Gi
"

If the minimum size is known in advance, one could restrict the UI input to this, i.e. I should not be able to enter anything lesser then 20 Gi. 

Cheers
Jason

### LINKED ISSUE #451: Adapt to new Gardener Resources
Gardener recently changed the Kubernetes Resources. We need to adapt the dashboard to work with the new resources.
See also https://github.com/gardener/gardener/pull/1284

### LINKED ISSUE #457: Adapt to new `core.gardener.cloud/v1alpha1` APIs
gardener/gardener#1430 is merged, and with it all resources are available in the the new `core.gardener.cloud/v1alpha1` API group. The old `garden.sapcloud.io/v1beta1` API group will be deprecated and removed in the next months. Please adapt your internals to using the new API group.

### LINKED ISSUE #464: gardener/dashboard could not show expired Kubernetes versions
Steps to reproduce:
1. Add a Kubernetes version in a CloudProfile with `expirationDate` <= `time.Now()`
2. Navigate to `Create Cluster` (`$HOST/namespace/$NAMESPACE/shoots/+`)
3. Ensure that the expired Kubernetes version is listed in the `Kubernetes versions` dropdown.

Ref gardener/gardener#1363

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #457 Fixes #451 Fixes #464 Fixes #118

**Special notes for your reviewer**:
Required as old Gardener API has been deprecated and we need to switch to the new resources.

**Release note**:

```action operator
Clusters will now be created using availability zones instead of availability sets on Azure. Please configure regions in your Azure cloud profile(s)
```
```noteworthy user
With this version we migrated the Dashboard to the new `core.gardener.cloud` API group. You will notice the different shoot resource when viewing the YAML configuration of your clusters
```
```improvement user
You can now configure zones for each worker group of your clusters
```
```improvement user
The creation of multi zone clusters is now fully supported by the Gardener Dashboard
```

### CODE REVIEW

File: backend/lib/services/cloudprofiles.js [hunk 1]
```diff
@@ -19,31 +19,40 @@
...
     .chain(seeds)
-    .filter(['spec.cloud.profile', cloudProfileName])
+    .filter(({ metadata, spec }) => {
+      if (spec.provider.type !== cloudProviderKind) {
+        return false
+      }
+      let seedMatchesLabelSelector = true
+      _.forEach(_.keys(matchLabels), key => {
+        if (!_.isEqual(matchLabels[key], _.get(metadata, ['labels', key]))) {
+          seedMatchesLabelSelector = false
```
Comment (grolu) [inline backend/lib/services/cloudprofiles.js]: return false

Comment (grolu) [reply backend/lib/services/cloudprofiles.js]: rm keys use of Object.entries

File: backend/lib/services/cloudprofiles.js [hunk 2]
```diff
@@ -52,37 +61,41 @@ exports.list = function () {
...
-      seeds: getSeedsForCloudProfileName({
+      seeds: getSeedsForCloudProfile({
         seeds,
-        cloudProfileName: cloudProfile.metadata.name
+        cloudProviderKind: cloudProfile.spec.type,
+        matchLabels: _.get(cloudProfile, 'spec.seedSelector.matchLabels')
       })
     }))
+    .filter((cloudProfile) => {
+      return cloudProfile.data.seeds.length > 0
```
Comment (grolu) [inline backend/lib/services/cloudprofiles.js]: one line

File: backend/lib/services/cloudprofiles.js [hunk 3]
```diff
@@ -52,37 +61,41 @@ exports.list = function () {
...
   const seeds = getVisibleAndNotProtectedSeeds()
+  const seedsForCloudProfile = getSeedsForCloudProfile({
+    seeds,
+    cloudProviderKind: cloudProfile.spec.type,
+    matchLabels: _.get(cloudProfile, 'spec.seedSelector.matchLabels', [])
+  })
 
-  const seedWithNameExists = _.findIndex(seeds, ['spec.cloud.profile', name]) !== -1
-  if (!seedWithNameExists) {
+  if (seedsForCloudProfile.length < 1) {
```
Comment (grolu) [inline backend/lib/services/cloudprofiles.js]: isEmpty

File: backend/lib/services/terminals/index.js [hunk 4]
```diff
@@ -196,7 +196,7 @@ async function getTargetCluster ({ user, namespace, name, target }) {
     case TargetEnum.CONTROL_PLANE: {
       const shootResource = await shoots.read({ user, namespace, name })
       const seedShootNS = getSeedShootNamespace(shootResource)
-      const seedName = shootResource.spec.cloud.seed
```
Comment (grolu) [inline backend/lib/services/terminals/index.js]: check status, throw?

File: backend/lib/services/terminals/index.js [hunk 5]
```diff
@@ -242,7 +242,11 @@ async function getSeedHostCluster ({ gardenClient, gardenCoreClient, namespace,
   }
 
   const seedShootNS = getSeedShootNamespace(shootResource)
-  const seedName = shootResource.spec.cloud.seed
+  const seedName = shootResource.status.seed
+
```
Comment (grolu) [inline backend/lib/services/terminals/index.js]: check status

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 6]
```diff
@@ -92,7 +92,7 @@ function seedShootNsExists (resource) {
     If the technicalID is set and the progress is over 10% (best guess), then we assume that the namespace on the seed exists for this shoot.
     Currently there is no better indicator, except trying to get the namespace on the seed - which we want to avoid for performance reasons.
   */
-  return _.get(resource, 'status.technicalID') && _.get(resource, 'status.lastOperation.progress', 0) > 10
+  return _.get(resource, 'status.technicalID') && _.get(resource, 'status.seed') && _.get(resource, 'status.lastOperation.progress', 0) > 10
```
Comment (grolu) [inline backend/lib/services/terminals/terminalBootstrap.js]: extract status

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 7]
```diff
@@ -245,15 +245,15 @@ async function ensureTrustedCertForShootApiServer ({ gardenClient, coreClient, n
   }
 
   // fetch seed resource
-  const seedName = shootResource.spec.cloud.seed
```
Comment (grolu) [inline backend/lib/services/terminals/terminalBootstrap.js]: check status, throw?

File: backend/lib/utils/index.js [hunk 8]
```diff
@@ -75,29 +75,18 @@ function encodeBase64 (value) {
...
-  return _.head(_.intersection(_.keys(object), cloudProviderKinds))
-}
-
 function shootHasIssue (shoot) {
   return _.get(shoot, ['metadata', 'labels', 'shoot.garden.sapcloud.io/status'], 'healthy') !== 'healthy'
 }
 
 async function getShootIngressDomain (projects, namespaces, shoot, seed = undefined) {
   if (!seed) {
-    seed = getSeed(shoot.spec.cloud.seed)
```
Comment (grolu) [inline backend/lib/utils/index.js]: check status, throw?

File: frontend/src/store/index.js [hunk 9]
```diff
@@ -289,12 +313,25 @@ const getters = {
...
       const cloudProfile = getters.cloudProfileByName(cloudProfileName)
-      return get(cloudProfile, 'data.kubernetes.versions', [])
+      const allVersions = get(cloudProfile, 'data.kubernetes.versions', [])
+      const validVersions = filter(allVersions, ({ expirationDate }) => {
+        return !expirationDate || moment().isBefore(expirationDate)
+      })
+      return map(validVersions, version => {
+        return {
+          ...version,
+          expirationDateString: getTimestampFormatted(version.expirationDate)
```
Comment (grolu) [inline frontend/src/store/index.js]: change to in ... with tooltip

File: frontend/src/components/NewShoot/NewShootDetails.vue [hunk 10]
```diff
@@ -166,7 +177,7 @@ export default {
       this.onInputPurpose()
     },
     setDefaultKubernetesVersion () {
-      this.kubernetesVersion = head(this.sortedKubernetesVersionsList)
+      this.kubernetesVersion = head(this.sortedKubernetesVersionsList).version
```
Comment (grolu) [inline frontend/src/components/NewShoot/NewShootDetails.vue]: use get

File: backend/lib/services/cloudprofiles.js (hunk 1 above)
Comment (grolu) [reply backend/lib/services/cloudprofiles.js]: done

File: backend/lib/services/cloudprofiles.js (hunk 2 above)
Comment (grolu) [reply backend/lib/services/cloudprofiles.js]: done

File: backend/lib/services/cloudprofiles.js (hunk 3 above)
Comment (grolu) [reply backend/lib/services/cloudprofiles.js]: done

File: backend/lib/services/terminals/index.js (hunk 4 above)
Comment (grolu) [reply backend/lib/services/terminals/index.js]: done

File: backend/lib/services/terminals/index.js (hunk 5 above)
Comment (grolu) [reply backend/lib/services/terminals/index.js]: done

File: backend/lib/services/terminals/terminalBootstrap.js (hunk 6 above)
Comment (grolu) [reply backend/lib/services/terminals/terminalBootstrap.js]: done

File: backend/lib/services/terminals/terminalBootstrap.js (hunk 7 above)
Comment (grolu) [reply backend/lib/services/terminals/terminalBootstrap.js]: done

File: backend/lib/utils/index.js (hunk 8 above)
Comment (grolu) [reply backend/lib/utils/index.js]: done

File: frontend/src/store/index.js (hunk 9 above)
Comment (grolu) [reply frontend/src/store/index.js]: part of #489

File: frontend/src/components/NewShoot/NewShootDetails.vue (hunk 10 above)
Comment (grolu) [reply frontend/src/components/NewShoot/NewShootDetails.vue]: done

File: frontend/src/components/ShootDetails/ShootInfrastructureCard.vue [hunk 11]
```diff
@@ -135,7 +135,7 @@ export default {
       return includes(this.namespaces, 'garden')
     },
     canLinkToSeed () {
-      return canLinkToSeed({ shootNamespace: this.namespace })
+      return canLinkToSeed({ shootNamespace: this.namespace, shootSeed: this.shootSeed })
```
Comment (grolu) [inline frontend/src/components/ShootDetails/ShootInfrastructureCard.vue]: rename to shootSeedName

File: frontend/src/components/ShootWorkers/ManageWorkers.vue [hunk 12]
```diff
@@ -86,25 +86,30 @@ export default {
...
-    volumeTypes () {
-      return this.volumeTypesByCloudProfileNameAndZones({ cloudProfileName: this.cloudProfileName, zones: this.zones })
+    allZones () {
+      return this.zonesByCloudProfileNameAndRegion({ cloudProfileName: this.cloudProfileName, region: this.region })
     },
-    defaultMachineImage () {
-      return this.defaultMachineImageForCloudProfileName(this.cloudProfileName)
+    availableZones () {
+      // Ensure that only zones can be selected, that have a network config in providerConfig (if required)
+      // Could be removed if gardener would support to change network config afterwards
```
Comment (grolu) [inline frontend/src/components/ShootWorkers/ManageWorkers.vue]: link gardener issue

File: frontend/src/components/ShootWorkers/ManageWorkers.vue [hunk 13]
```diff
@@ -86,25 +86,30 @@ export default {
...
+      const zonesWithNetworkConfigInShoot = map(this.zonesNetworkConfiguration, 'name')
+      if (zonesWithNetworkConfigInShoot.length > 0) {
```
Comment (grolu) [inline frontend/src/components/ShootWorkers/ManageWorkers.vue]: !empty

File: frontend/src/components/ShootWorkers/ManageWorkers.vue [hunk 14]
```diff
@@ -172,7 +162,7 @@ export default {
     getWorkers () {
       const workers = []
       forEach(this.internalWorkers, internalWorker => {
```
Comment (grolu) [inline frontend/src/components/ShootWorkers/ManageWorkers.vue]: use map

File: frontend/src/components/ShootWorkers/ManageWorkers.vue [hunk 15]
```diff
@@ -188,23 +178,27 @@ export default {
...
+      this.region = region
+      this.zonesNetworkConfiguration = zonesNetworkConfiguration
       this.setInternalWorkers(workers)
     }
   },
   mounted () {
     if (this.userInterActionBus) {
       this.userInterActionBus.on('updateCloudProfileName', cloudProfileName => {
+        this.internalWorkers = []
         this.cloudProfileName = cloudProfileName
```
Comment (grolu) [inline frontend/src/components/ShootWorkers/ManageWorkers.vue]: rm nexttick?

File: frontend/src/components/ShootWorkers/WorkerConfiguration.vue [hunk 16]
```diff
@@ -79,9 +81,10 @@ export default {
     reset () {
       this.workersValid = false
 
-      const workers = this.shootWorkerGroups
+      const workers = cloneDeep(this.shootWorkerGroups)
+      const zonesNetworkConfiguration = get(this.shootItem, 'spec.provider.infrastructureConfig.networks.zones')
       this.$nextTick(() => {
-        this.$refs.manageWorkers.setWorkersData({ workers, cloudProfileName: this.shootCloudProfileName, zones: this.shootZones })
+        this.$refs.manageWorkers.setWorkersData({ workers, cloudProfileName: this.shootCloudProfileName, region: this.shootRegion, zonesNetworkConfiguration })
```
Comment (grolu) [inline frontend/src/components/ShootWorkers/WorkerConfiguration.vue]: rm nexttick?

File: frontend/src/components/ShootDetails/ShootInfrastructureCard.vue (hunk 11 above)
Comment (grolu) [reply frontend/src/components/ShootDetails/ShootInfrastructureCard.vue]: done

File: frontend/src/components/ShootWorkers/ManageWorkers.vue (hunk 12 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/ManageWorkers.vue]: PR linked

File: frontend/src/components/ShootWorkers/ManageWorkers.vue (hunk 13 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/ManageWorkers.vue]: done

File: frontend/src/components/ShootWorkers/ManageWorkers.vue (hunk 14 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/ManageWorkers.vue]: done

File: frontend/src/components/ShootWorkers/ManageWorkers.vue (hunk 15 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/ManageWorkers.vue]: removed

File: frontend/src/components/ShootWorkers/WorkerConfiguration.vue (hunk 16 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerConfiguration.vue]: will not remove right now, filed an issue #491

File: frontend/src/store/index.js [hunk 17]
```diff
@@ -230,25 +244,35 @@ const getters = {
       return uniq(map(get(cloudProfile, 'data.seeds'), 'data.region'))
     }
   },
+  minimumVolumeSizeByCloudProfileNameAndRegion (state, getters) {
+    return ({ cloudProfileName, region }) => {
+      const cloudProfile = getters.cloudProfileByName(cloudProfileName)
+      const seedsForCloudProfile = cloudProfile.data.seeds
+      const seedsMatchingCloudProfileAndRegion = find(seedsForCloudProfile, { data: { region } })
+      return min(map(seedsMatchingCloudProfileAndRegion, 'volume.minimumSize')) || '20Gi'
```
Comment (grolu) [inline frontend/src/store/index.js]: use max
convert to Gi

File: frontend/src/mixins/shootItem.js [hunk 18]
```diff
@@ -72,34 +73,31 @@ export const shootItem = {
       return isHibernated(this.shootSpec)
     },
     shootSecret () {
```
Comment (grolu) [inline frontend/src/mixins/shootItem.js]: rename to secretbindingname

File: frontend/src/mixins/shootItem.js [hunk 19]
```diff
@@ -72,34 +73,31 @@ export const shootItem = {
...
     shootAddons () {
       return get(this.shootSpec, 'addons', {})
     },
     shootRegion () {
-      return get(this.shootSpec, 'cloud.region')
+      return this.shootSpec.region
     },
     shootZones () {
-      return get(this.shootSpec, ['cloud', this.shootCloudProviderKind, 'zones'], [])
+      return uniq(flatMap(get(this.shootSpec, 'provider.workers', []), 'zones'))
```
Comment (grolu) [inline frontend/src/mixins/shootItem.js]: rm default

File: frontend/src/store/index.js [hunk 20]
```diff
@@ -289,12 +313,25 @@ const getters = {
   kubernetesVersions (state, getters) {
     return (cloudProfileName) => {
       const cloudProfile = getters.cloudProfileByName(cloudProfileName)
-      return get(cloudProfile, 'data.kubernetes.versions', [])
+      const allVersions = get(cloudProfile, 'data.kubernetes.versions', [])
```
Comment (grolu) [inline frontend/src/store/index.js]: rm default

File: frontend/src/store/modules/shoots.js [hunk 21]
```diff
@@ -226,37 +227,36 @@ const actions = {
...
   resetNewShootResource ({ commit, rootState, rootGetters }) {
     const shootResource = {
-      apiVersion: 'garden.sapcloud.io/v1beta1',
-      kind: 'Shoot'
+      apiVersion: 'core.gardener.cloud/v1alpha1',
+      kind: 'Shoot',
+      metadata: {},
+      spec: {
+        networking: {
+          type: 'calico',
```
Comment (grolu) [inline frontend/src/store/modules/shoots.js]: add TODO

File: frontend/src/store/modules/shoots.js [hunk 22]
```diff
@@ -350,9 +347,9 @@ const getRawVal = (item, column) => {
     case 'k8sVersion':
       return get(spec, 'kubernetes.version')
     case 'infrastructure':
-      return `${getCloudProviderKind(spec.cloud)} ${get(spec, 'cloud.region')}`
+      return get(spec, 'provider.type')
```
Comment (grolu) [inline frontend/src/store/modules/shoots.js]: add region

Comment (grolu) [reply frontend/src/store/modules/shoots.js]: return array, sort separately

File: frontend/src/mixins/shootItem.js (hunk 18 above)
Comment (grolu) [reply frontend/src/mixins/shootItem.js]: done

File: frontend/src/store/index.js (hunk 20 above)
Comment (grolu) [reply frontend/src/store/index.js]: done

File: frontend/src/store/modules/shoots.js (hunk 21 above)
Comment (grolu) [reply frontend/src/store/modules/shoots.js]: done

File: frontend/src/store/index.js (hunk 17 above)
Comment (grolu) [reply frontend/src/store/index.js]: filed issue for conversion

File: frontend/src/mixins/shootItem.js (hunk 19 above)
Comment (grolu) [reply frontend/src/mixins/shootItem.js]: done

File: frontend/src/store/modules/shoots.js (hunk 22 above)
Comment (grolu) [reply frontend/src/store/modules/shoots.js]: filed issue for separate sorting
