### PR TITLE
fix: theme (dark/light) not correctly applied on first visit

### LINKED ISSUE #1324: Initial "auto choose theme based on system settings" does not work
**What happened**:
Initially the "auto choose theme based on system settings" does not work when you have configured a dark theme on OS level

**What you expected to happen**:
It should adapt the theme based on the system setting

**How to reproduce it (as minimally and precisely as possible)**:
- Set a dark theme on OS level
- Delete local storage in your browsers console
- Reload the dashboard

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by sven-petersen**
**What this PR does / why we need it**:

Upon first visit of the page the users system/OS wide preferred color theme was not correctly applied. Additionally dark mode users that first to explicitly select "light" mode and only then could switch to dark mode or auto.

**Which issue(s) this PR fixes**:
Fixes #1324

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Fixed initial "auto choose theme based on system settings" not working
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @sven-petersen for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

File: frontend/src/store/index.js [hunk 1]
```diff
@@ -164,7 +164,7 @@ const state = {
       description: 'Indicates whether Gardener is able to hibernate this cluster. If you do not resolve this issue your hibernation schedule may not have any effect.'
     }
   },
-  prefersColorScheme: 'light'
+  prefersColorScheme: window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
```
Comment (holgerkoser) [inline frontend/src/store/index.js:167]:
```suggestion
  prefersColorScheme: 'light'
```
We don't want to have a media query dependency here. This is why we have the mediaPlugin.

File: frontend/src/store/modules/storage.js [hunk 2]
```diff
@@ -7,7 +7,9 @@
 import Vue from 'vue'
 
 // initial state
-const state = {}
+const state = {
+  'global/color-scheme': 'auto'
+}
```
Comment (holgerkoser) [inline frontend/src/store/modules/storage.js:12]:
```suggestion
const state = {}
```
The state of the storage module is initialized in the storage plugin

File: frontend/src/store/plugins/mediaPlugin.js [hunk 3]
```diff
@@ -11,12 +11,13 @@ export default function (vuetify) {
...
     mq.addEventListener('change', e => setPrefersColorScheme(e.matches))
-    setPrefersColorScheme(mq.matches)
 
     const colorScheme = (state, getters) => getters.colorScheme
     const setDarkTheme = value => {
       vuetify.framework.theme.dark = value === 'dark'
     }
     store.watch(colorScheme, setDarkTheme)
+    // theme by default is set to light. Hence only need to change it if we want the dark theme
+    if (store.getters.colorScheme === 'dark') setDarkTheme('dark')
```
Comment (holgerkoser) [inline frontend/src/store/plugins/mediaPlugin.js:21]:
```suggestion
    // initialize the vuetify dark theme value
    setDarkTheme(store.getters.colorScheme)
```

File: frontend/src/store/index.js [hunk 4]
```diff
@@ -97,17 +97,16 @@ const debug = includes(split(process.env.VUE_APP_DEBUG, ','), 'vuex')
...
 ]
 // localStorage can be undefined in some unit tests
 if (localStorage) {
   plugins.push(createStoragePlugin(localStorage))
 }
+plugins.push(createMediaPlugin(vuetify))
 if (debug) {
   plugins.push(createLogger())
 }
-
```
Comment (holgerkoser) [inline frontend/src/store/index.js:110]: keep the empty line

File: frontend/src/store/plugins/mediaPlugin.js [hunk 5]
```diff
@@ -6,17 +6,20 @@
...
-
-    const colorScheme = (state, getters) => getters.colorScheme
+    mq.addEventListener('change', e => setPrefersColorScheme(e.matches))
+   
+    // apply the theme initially and watch for changes
     const setDarkTheme = value => {
       vuetify.framework.theme.dark = value === 'dark'
     }
+    const colorScheme = (state, getters) => getters.colorScheme
+    setDarkTheme(store.getters.colorScheme)
```
Comment (holgerkoser) [inline frontend/src/store/plugins/mediaPlugin.js:22]: This was missing in the original code and that was the reason why it has not worked. The other changes do not change anything. I do not like code comments, if the code is self explaining https://medium.com/@bpnorlander/stop-writing-code-comments-28fef5272752.

Comment (holgerkoser) [reply frontend/src/store/plugins/mediaPlugin.js:22]: > There are only four situations I can think of at the moment where I need to comment code:
> 
> 1. In the styles of Javadoc, RubyDoc, et cetera for documenting APIs others will use.
> 2. In the off chance it really is that complex: For example, on a bioinformatics DNA search function that took 5 weeks to formulate and write out. That’s how rare it is to have something complex enough to warrant comments.
> 3. TODOs, which should be the exception, not the rule
> 4. Explaining why the most obvious code wasn’t written. (Design decisions)
> 

[Sam Larbi](http://www.codeodor.com/index.cfm/2008/6/18/Common-Excuses-Used-To-Comment-Code-and-What-To-Do-About-Them/2293)

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Review by petersutter — APPROVED** [review]
/lgtm

**Comment by petersutter** [comment]
however the tests failed
```
#24 26.87 Summary of all failing tests
#24 26.87 FAIL tests/unit/store.shoots.spec.js
#24 26.87   ● Test suite failed to run
#24 26.87 
#24 26.87     TypeError: Cannot read properties of undefined (reading 'framework')
#24 26.87 
#24 26.87       16 |     const colorScheme = (state, getters) => getters.colorScheme
#24 26.87       17 |     const setDarkTheme = value => {
#24 26.87     > 18 |       vuetify.framework.theme.dark = value === 'dark'
#24 26.87          |               ^
#24 26.87       19 |     }
#24 26.87       20 |     setDarkTheme(store.getters.colorScheme)
#24 26.87       21 |     store.watch(colorScheme, setDarkTheme)
#24 26.87 
#24 26.87       at setDarkTheme (src/store/plugins/mediaPlugin.js:18:15)
#24 26.87       at plugin (src/store/plugins/mediaPlugin.js:20:5)
#24 26.87       at forEach (../.yarn/__virtual__/vuex-virtual-0cf1f98312/0/cache/vuex-npm-3.6.2-82badaae22-37915741ba.zip/node_modules/vuex/dist/vuex.common.js:429:46)
#24 26.87           at Array.forEach (<anonymous>)
#24 26.87       at new Store (../.yarn/__virtual__/vuex-virtual-0cf1f98312/0/cache/vuex-npm-3.6.2-82badaae22-37915741ba.zip/node_modules/vuex/dist/vuex.common.js:429:11)
#24 26.87       at Object.<anonymous> (src/store/index.js:1638:15)
#24 26.87       at Object.<anonymous> (tests/unit/store.shoots.spec.js:7:1)
#24 26.87 
#24 26.87 FAIL tests/unit/StatusTags.spec.js
#24 26.87   ● Test suite failed to run
#24 26.87 
#24 26.87     TypeError: Cannot read properties of undefined (reading 'framework')
#24 26.87 
#24 26.87       16 |     const colorScheme = (state, getters) => getters.colorScheme
#24 26.87       17 |     const setDarkTheme = value => {
#24 26.87     > 18 |       vuetify.framework.theme.dark = value === 'dark'
#24 26.87          |               ^
#24 26.87       19 |     }
#24 26.87       20 |     setDarkTheme(store.getters.colorScheme)
#24 26.87       21 |     store.watch(colorScheme, setDarkTheme)
#24 26.87 
#24 26.87       at setDarkTheme (src/store/plugins/mediaPlugin.js:18:15)
#24 26.87       at plugin (src/store/plugins/mediaPlugin.js:20:5)
#24 26.87       at forEach (../.yarn/__virtual__/vuex-virtual-0cf1f98312/0/cache/vuex-npm-3.6.2-82badaae22-37915741ba.zip/node_modules/vuex/dist/vuex.common.js:429:46)
#24 26.88           at Array.forEach (<anonymous>)
#24 26.88       at new Store (../.yarn/__virtual__/vuex-virtual-0cf1f98312/0/cache/vuex-npm-3.6.2-82badaae22-37915741ba.zip/node_modules/vuex/dist/vuex.common.js:429:11)
#24 26.88       at Object.<anonymous> (src/store/index.js:1638:15)
#24 26.88       at Object.<anonymous> (tests/unit/StatusTags.spec.js:18:1)
#24 26.88 
#24 26.88 FAIL tests/unit/utils.spec.js
#24 26.88   ● Test suite failed to run
#24 26.88 
#24 26.88     TypeError: Cannot read properties of undefined (reading 'framework')
#24 26.88 
#24 26.88       16 |     const colorScheme = (state, getters) => getters.colorScheme
#24 26.88       17 |     const setDarkTheme = value => {
#24 26.88     > 18 |       vuetify.framework.theme.dark = value === 'dark'
#24 26.88          |               ^
#24 26.88       19 |     }
#24 26.88       20 |     setDarkTheme(store.getters.colorScheme)
#24 26.88       21 |     store.watch(colorScheme, setDarkTheme)
#24 26.88 
#24 26.88       at setDarkTheme (src/store/plugins/mediaPlugin.js:18:15)
#24 26.88       at plugin (src/store/plugins/mediaPlugin.js:20:5)
#24 26.88       at forEach (../.yarn/__virtual__/vuex-virtual-0cf1f98312/0/cache/vuex-npm-3.6.2-82badaae22-37915741ba.zip/node_modules/vuex/dist/vuex.common.js:429:46)
#24 26.88           at Array.forEach (<anonymous>)
#24 26.88       at new Store (../.yarn/__virtual__/vuex-virtual-0cf1f98312/0/cache/vuex-npm-3.6.2-82badaae22-37915741ba.zip/node_modules/vuex/dist/vuex.common.js:429:11)
#24 26.88       at Object.<anonymous> (src/store/index.js:1638:15)
#24 26.88       at Object.<anonymous> (tests/unit/utils.spec.js:9:1)
#24 26.88 
#24 26.88 FAIL tests/unit/store.index.spec.js
#24 26.88   ● Test suite failed to run
#24 26.88 
#24 26.88     TypeError: Cannot read properties of undefined (reading 'framework')
#24 26.88 
#24 26.88       16 |     const colorScheme = (state, getters) => getters.colorScheme
#24 26.88       17 |     const setDarkTheme = value => {
#24 26.89     > 18 |       vuetify.framework.theme.dark = value === 'dark'
#24 26.89          |               ^
#24 26.89       19 |     }
#24 26.89       20 |     setDarkTheme(store.getters.colorScheme)
#24 26.89       21 |     store.watch(colorScheme, setDarkTheme)
#24 26.89 
#24 26.89       at setDarkTheme (src/store/plugins/mediaPlugin.js:18:15)
#24 26.89       at plugin (src/store/plugins/mediaPlugin.js:20:5)
#24 26.89       at forEach (../.yarn/__virtual__/vuex-virtual-0cf1f98312/0/cache/vuex-npm-3.6.2-82badaae22-37915741ba.zip/node_modules/vuex/dist/vuex.common.js:429:46)
#24 26.89           at Array.forEach (<anonymous>)
#24 26.89       at new Store (../.yarn/__virtual__/vuex-virtual-0cf1f98312/0/cache/vuex-npm-3.6.2-82badaae22-37915741ba.zip/node_modules/vuex/dist/vuex.common.js:429:11)
#24 26.89       at Object.<anonymous> (src/store/index.js:1638:15)
#24 26.89       at Object.<anonymous> (tests/unit/store.index.spec.js:6:1)
```

**Comment by holgerkoser** [comment]
The tests are failing because vuetify is not available in the tests but it is initialized now. A quick fix would be:
```js
const setDarkTheme = value => {
  if (vuetify) {
    vuetify.framework.theme.dark = value === 'dark'
  }
}
```

**Review by grolu — APPROVED** [review]
/lgtm
