### PR TITLE
Fix markdown converter initialization if no gitHub.apiUrl is configured

### LINKED ISSUE #896: Cannot read property 'apiUrl' of undefined
**What happened**:
When the dashboard is does not have a github configuration for the ticket feature, the backend fails to start with the error:

```bash
dashboard/backend/lib/services/tickets.js:26
  ghMentionsLink: new URL(config.gitHub.apiUrl).origin + '/{u}'
                                        ^
```

**What you expected to happen**:
The dashboard starts even if no github configuration is set.

**How to reproduce it (as minimally and precisely as possible)**:
Do not configure `github` property start the dashbaord

**Anything else we need to know**:
This issue does not occur on one of the released dashboard versions. It's only present for the `master` branch

**Environment**:

### PR DESCRIPTION
**Pull request by NotTheEvilOne**
**What this PR does / why we need it**:
This PR validates the existence of "config.gitHub.apiUrl" before usage.

**Which issue(s) this PR fixes**:
Fixes #896

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @NotTheEvilOne for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

File: backend/lib/services/tickets.js [hunk 1]
```diff
@@ -21,10 +21,12 @@ function fromLabel (item) {
...
-const converter = exports.converter = markdown.createConverter({
-  ghMentions: true,
-  ghMentionsLink: new URL(config.gitHub.apiUrl).origin + '/{u}'
-})
+const converter = exports.converter = markdown.createConverter(
+  _.get(config, 'gitHub.apiUrl') ? {
+    ghMentions: true,
+    ghMentionsLink: new URL(config.gitHub.apiUrl).origin + '/{u}'
+  } : { }
+)
```
Comment (petersutter) [inline backend/lib/services/tickets.js:29]: extract options to variable to make it more readable
```js
const options = {}
const apiUrl = _.get(config, 'gitHub.apiUrl')
if (apiUrl) {
  options.ghMentions = true
  options.ghMentionsLink = new URL(apiUrl).origin + '/{u}'
}
const converter = exports.converter = markdown.createConverter(options)
```

Comment (NotTheEvilOne) [reply backend/lib/services/tickets.js:29]: Will do so.

**Review by petersutter — APPROVED** [review]
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm

**Review by holgerkoser — APPROVED** [review]
/lgtm
