### PR TITLE
[master] Improve terminal bootstrapping

### LINKED ISSUE #745: Terminal bootstrapping hangs
**What happened**:
It could happen that the terminal bootstrapping hangs and that no more tasks are run from the queue, in case the queue was not configured with a timeout for the tasks. Only killing / restarting the pod helps to re-start the terminal bootstrapping.

When running a task to bootstrap e.g. a shoot we we could see from the logs that a POST request was initiated to create the ingress for the `kube-apiserver` but it never returned and thus the task never finished.

The current assumption is that the `got` library that we use for the http requests has a bug that causes requests in some cases to not return (e.g. `resolve` / `reject` not called for promise) and we should upgrade to the latest `got` version.

In addition we have to set, by default, a timeout for the tasks on the queue

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
This PR improves the terminal bootstrapping
- Adds default timeout of 10 minutes to the bootstrapping task (currently there is a bug in the `got` http request library where requests get stuck and do not return/timeout)
- Stores in-memory which shoots were already processed successfully. Previously all shoots were added to the queue on connection loss / when the watch restarts.
- Cancels the task in case the shoot gets deleted

**Which issue(s) this PR fixes**:
Fixes #745 

**Special notes for your reviewer**:
In a second iteration (not part of this PR), the set of successfully bootstrapped shoots could be stored when the dashboard shuts down gracefully and restored once it starts again.

**Release note**:

```improvement user

```

### CODE REVIEW

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 1]
```diff
@@ -53,39 +54,70 @@ const { getSeed } = require('../../cache')
...
+  addResourceWithKey (key) {
     this.add(key)
     return key
   }
 }
 
+class BootstrapPendingSet extends BootstrapSet {
+  static keyForResource (resource) {
+    const kind = resource.kind
+    const { metadata: { name, namespace } } = resource
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:86]:
```suggestion
  static keyForResource ({ kind, metadata: { name, namespace } }) {
```

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 2]
```diff
@@ -53,39 +54,70 @@ const { getSeed } = require('../../cache')
 
 const TERMINAL_KUBE_APISERVER = 'dashboard-terminal-kube-apiserver'
 
-class BootstrapPendingSet extends Set {
-  _keyForResource (resource) {
-    const kind = resource.kind
-    const { metadata: { name, namespace } } = resource
-    return `${kind}/${namespace}/${name}`
+class BootstrapSet extends Set {
+  static keyForResource () {
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:58]: Pseudo abstract class in javascript? I would use a default implementation.

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 3]
```diff
@@ -53,39 +54,70 @@ const { getSeed } = require('../../cache')
...
+class BootstrappedSet extends BootstrapSet {
+  static keyForResource (resource) {
+    const { metadata: { uid } } = resource
+    return uid
+  }
+}
+
+function taskIdForResource (resource) {
+  const { metadata: { uid } } = resource
+  return uid
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:100]: return this.constructor.keyForResource(resource)

Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:100]:
```suggestion
return this.constructor.keyForResource(resource)
```

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 4]
```diff
@@ -53,39 +54,70 @@ const { getSeed } = require('../../cache')
...
+}
+
 class Handler {
-  constructor (fn, description) {
+  constructor ({ id, fn, description }) {
+    this.id = id
     this.fn = fn
-    this._run = () => fn()
+    this._run = session => fn(session)
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:107]: Why do we store the session on the handler if we pass it to the run method. Or the other way around. Why do we pass the session to the run method if we store it on the handler?

Comment (petersutter) [reply backend/lib/services/terminals/terminalBootstrap.js:107]: so that we can cancel it later on?

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 5]
```diff
@@ -53,39 +54,70 @@ const { getSeed } = require('../../cache')
...
+}
+
+function taskIdForResource (resource) {
+  const { metadata: { uid } } = resource
+  return uid
+}
+
 class Handler {
-  constructor (fn, description) {
+  constructor ({ id, fn, description }) {
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:104]: `fn` is not a good name for a named paramter

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 6]
```diff
@@ -432,7 +499,12 @@ class Bootstrapper extends Queue {
   }
 
   bootstrapResource (resource) {
-    const kind = resource.kind
+    const {
+      kind,
+      metadata: { namespace, name, uid }
+    } = resource
+    const description = `${kind} - ${namespace ? namespace + '/' : ''}${name} (${uid})`
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:506]:
```suggestion
    const qualifiedName = namespace ? namespace + '/' + name : name
    const description = `${kind} - ${qualifiedName} (${uid})`
```

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 7]
```diff
@@ -455,44 +530,79 @@ class Bootstrapper extends Queue {
...
+      id: taskId, // with the id we make sure that the task for one shoot is not added multiple times (e.g. on another ADDED event when the shoot watch is re-established)
+      fn: async session => {
+        if (session.canceled) {
+          logger.debug(`Canceling handler of ${description} as requested`)
+          return
+        }
+
+        switch (kind) {
+          case 'Seed': {
+            await handleSeed({ name })
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:554]: why no try catch

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 8]
```diff
@@ -455,44 +530,79 @@ class Bootstrapper extends Queue {
...
+      try {
+        await handler.run()
+        cb(null, null)
+      } catch (err) {
+        logger.error(`failed to bootstrap ${handler.description}`, err)
+        cb(err, null)
+      }
+    })()
+    return {
+      cancel: function () {
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:602]:
```suggestion
      cancel () {
```

File: backend/lib/services/terminals/terminalBootstrap.js (hunk 5 above)
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:104]:
```suggestion
  constructor (fn, { id, description }) {
```

Comment (holgerkoser) [reply backend/lib/services/terminals/terminalBootstrap.js:104]: the handler function is mandatory. Id and description seem to be optional.

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 9]
```diff
@@ -402,10 +432,11 @@ class Bootstrapper extends Queue {
   constructor () {
     super(Bootstrapper.process, Bootstrapper.options)
     this.bootstrapPending = new BootstrapPendingSet()
+    this.bootstrapped = new BootstrappedSet()
     this.requiredConfigExists = verifyRequiredConfigExists()
     if (this.isBootstrapKindAllowed('gardenTerminalHost')) {
       const description = 'garden host cluster'
-      const handler = new Handler(ensureTrustedCertForGardenTerminalHostApiServer, description)
+      const handler = new Handler({ id: 'gardenTerminalHost', fn: ensureTrustedCertForGardenTerminalHostApiServer, description })
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:439]:
```suggestion
      const handler = new Handler(ensureTrustedCertForGardenTerminalHostApiServer, { 
        id: 'gardenTerminalHost', 
        description 
      })
```

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 10]
```diff
@@ -455,44 +530,79 @@ class Bootstrapper extends Queue {
...
+
+        if (session.canceled) { // do not add key to the bootstrapped set when the session is canceled (due to shoot deletion) to prevent leaking memory
+          logger.debug(`Canceling handler of ${description} as requested after handling resource`)
+          return
+        }
+        logger.debug(`Successfully bootstrapped ${description}`)
+        this.bootstrapped.addResourceWithKey(key)
+      },
+      description
+    })
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:575]:
```suggestion
    const fn = async session => {
        if (session.canceled) {
          logger.debug(`Canceling handler of ${description} as requested`)
          return
        }

        switch (kind) {
          case 'Seed': {
            await handleSeed({ name })
            break
          }
          case 'Shoot': {
            await handleShoot({ name, namespace })
            break
          }
          default: {
            logger.error(`can't bootstrap unsupported kind ${kind}`)
            return
          }
        }

        if (session.canceled) { // do not add key to the bootstrapped set when the session is canceled (due to shoot deletion) to prevent leaking memory
          logger.debug(`Canceling handler of ${description} as requested after handling resource`)
          return
        }
        logger.debug(`Successfully bootstrapped ${description}`)
        this.bootstrapped.addResourceWithKey(key)
      }
    const handler = new Handler(fn, {
      id: taskId, // with the id we make sure that the task for one shoot is not added multiple times (e.g. on another ADDED event when the shoot watch is re-established)
      description
    })
```

File: backend/test/services.terminals.spec.js [hunk 11]
```diff
@@ -659,7 +662,7 @@ describe('services', function () {
         const seed = getSeed(seedName)
         createConfigStub({ bootstrap })
         const bootstrapper = new Bootstrapper()
-        bootstrapper.push(new Handler(() => {}, 'test'))
+        bootstrapper.push(new Handler({ fn: () => {}, description: 'test' }))
```
Comment (holgerkoser) [inline backend/test/services.terminals.spec.js:665]:
```suggestion
        bootstrapper.push(new Handler(() => {}, { description: 'test' }))
```

File: backend/lib/services/terminals/terminalBootstrap.js (hunk 8 above)
Comment (holgerkoser) [reply backend/lib/services/terminals/terminalBootstrap.js:602]: Or return the handler?

File: backend/lib/services/terminals/terminalBootstrap.js [hunk 12]
```diff
@@ -455,44 +530,79 @@ class Bootstrapper extends Queue {
...
 
-  static async process (handler, cb) {
-    try {
-      await handler.run()
-      cb(null, null)
-    } catch (err) {
-      logger.error(`failed to bootstrap ${handler.description}`, err)
-      cb(err, null)
+  static process (handler, cb) {
+    (async () => {
```
Comment (holgerkoser) [inline backend/lib/services/terminals/terminalBootstrap.js:592]: Move the background processing into handler run?
