### PR TITLE
Remove oidc configuration from necessary config (#727)

### LINKED ISSUE #727: OIDC configuration must not be mandatory
**What happened**:
The dashboard works without `oidc` configuration but when configuration is loaded an error is thrown `oidc` configuration properties are missing. The `oidc` configuration validation should be skipped if the `oidc` configuration is completely empty.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by morremeyer**
**What this PR does / why we need it**: Removes the OIDC configuration parameters from the list of required configuration variables as OIDC is not strictly required (dashboard can also be used with a bearer token)

**Which issue(s) this PR fixes**:
Fixes #727 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Removed OIDC configuration settings from necessary configuration as the dashboard can also be used with a bearer token
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @morremeyer for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

File: backend/lib/config/gardener.js [hunk 1]
```diff
@@ -88,11 +88,7 @@ module.exports = {
     this.assignEnvironmentVariables(config, env)
     const requiredConfigurationProperties = [
       'sessionSecret',
-      'apiServerUrl',
-      'oidc.issuer',
-      'oidc.client_id',
-      'oidc.client_secret',
-      'oidc.redirect_uri'
+      'apiServerUrl'
```
Comment (petersutter) [inline backend/lib/config/gardener.js:91]: > The oidc configuration validation should be skipped if the oidc configuration is completely empty.
please check if `config.oidc` is set. If yes, the oidc properties should be added to the required configuration properties

Comment (holgerkoser) [reply backend/lib/config/gardener.js:91]: It could look like this:
```js
const requiredConfigurationProperties = [
  'sessionSecret',
  'apiServerUrl'
]
if (config.oidc) {
  requiredConfigurationProperties.push(...[
      'oidc.issuer',	
      'oidc.client_id',	
      'oidc.client_secret',	
      'oidc.redirect_uri'
  ])
}
```

Comment (morremeyer) [reply backend/lib/config/gardener.js:91]: @holgerkoser That’s almost exactly what I implemented. Aren’t the square brackets in `.push([])` in your example superfluous?

**Review by petersutter — APPROVED** [review]
/lgtm

**Review by holgerkoser — APPROVED** [review]
/lgtm
