### PR TITLE
Handle unreachable seeds

### LINKED ISSUE #826: No error is shown in case of error when fetching the seed info
**What happened**:
No error is shown in case of error when fetching the seed info. The error was catched and logged in the backend.

**What you expected to happen**:
It should be clear to the user that fetching the information (e.g. monitoring credentials) has failed

**How to reproduce it (as minimally and precisely as possible)**:
As operator, navigate on the shoot details page of a cluster that is using an infrastructure that is not reachable from the gardener dashboard

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
This PR handles unreachable seeds
- Terminal feature is disabled in case the seed is not reachable by the dashboard
- A hint is shown that the monitoring credentials can't be fetched in case the seed is not reachable by the dashboard (only applies for operators)
Screenshot 2020-10-14 at 21 31 03

example `values.yaml`
```yaml
unreachableSeeds:
  matchLabels:
    seed.gardener.cloud/network: private
```

example seed:
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  labels:
    seed.gardener.cloud/network: private
    gardener.cloud/role: seed
  name: my-seed
spec:
  ...
```

**Which issue(s) this PR fixes**:
Fixes #826 

**Special notes for your reviewer**:

**Release note**:

```improvement user
We are now handling the case when seed is not reachable by the dashboard backend
- Terminal feature is disabled
- A hint is shown that the monitoring credentials can't be fetched in case the seed is not reachable by the dashboard (only applies for operators)
```

```action operator
Seeds that are unreachable by the dashboard need to be flagged as such with a corresponding label. This label needs be manifested in the dashboard configuration under the property `unreachableSeeds.matchLabels` in the `values.yaml` file
```

### CODE REVIEW

File: frontend/src/store/modules/seeds.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+  all: []
+}
+
+// getters
+const getters = {
+  items: state => state.all,
+  seedByName: (state) => (name) => {
+    const predicate = item => item.metadata.name === name
+    return find(state.all, predicate)
+  }
```
Comment (holgerkoser) [inline frontend/src/store/modules/seeds.js:31]:
```suggestion
  items (state) {
    return state.all
  },
  seedByName (state) {
    return name => find(state.all, ['metadata.name', name])
  }
```

File: frontend/src/store/modules/seeds.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+
+// actions
+const actions = {
+  getAll: ({ commit, rootState }) => {
+    return getSeeds()
+      .then(res => {
+        commit('RECEIVE', res.data)
+        return state.all
+      })
+  }
```
Comment (holgerkoser) [inline frontend/src/store/modules/seeds.js:42]:
```suggestion
  async getAll ({ commit, state }) {
    const { data } = await getSeeds()
    commit('RECEIVE', res.data)
    return state.all
  }
```

File: frontend/src/store/index.js [hunk 3]
```diff
@@ -936,6 +957,12 @@ const actions = {
         dispatch('setError', err)
       })
   },
+  fetchSeeds ({ dispatch }) {
+    return dispatch('seeds/getAll')
+      .catch(err => {
+        dispatch('setError', err)
+      })
+  },
```
Comment (holgerkoser) [inline frontend/src/store/index.js:965]:
```suggestion
  async fetchSeeds ({ dispatch }) {
    try {
      await dispatch('seeds/getAll')
    } catch (err) {
      dispatch('setError', err)
    }
  },
```

File: frontend/src/store/index.js [hunk 4]
```diff
@@ -571,15 +586,21 @@ const getters = {
...
+      const seeds = getters.seedsByNames(seedNames)
       const uniqueSeedRegions = uniq(map(seeds, 'data.region'))
       const uniqueSeedRegionsWithZones = filter(uniqueSeedRegions, isValidRegion(getters, cloudProfileName, cloudProfile.metadata.cloudProviderKind))
       return uniqueSeedRegionsWithZones
     }
   },
+  seedsByNames (state, getters) {
+    return (seedNames) => {
+      return map(seedNames, getters.seedByName)
+    }
```
Comment (holgerkoser) [inline frontend/src/store/index.js:602]:
```suggestion
    return seedNames => map(seedNames, getters.seedByName)
```

File: frontend/src/store/index.js [hunk 5]
```diff
@@ -316,11 +317,25 @@ const getters = {
...
+  },
   cloudProfileByName (state, getters) {
     return (name) => {
       return getters['cloudProfiles/cloudProfileByName'](name)
     }
   },
+  seedByName (state, getters) {
+    return (name) => {
+      return getters['seeds/seedByName'](name)
+    }
```
Comment (holgerkoser) [inline frontend/src/store/index.js:331]:
```suggestion
    return name) => getters['seeds/seedByName'](name)
```

File: frontend/src/store/index.js [hunk 6]
```diff
@@ -316,11 +317,25 @@ const getters = {
...
+  },
+  isSeedUnreachableByName (state, getters) {
+    return (name) => {
```
Comment (holgerkoser) [inline frontend/src/store/index.js:334]:
```suggestion
    return name => {
```

File: frontend/src/store/index.js (hunk 5 above)
Comment (holgerkoser) [inline frontend/src/store/index.js:331]:
```suggestion
    return name => getters['seeds/seedByName'](name)
```

File: frontend/src/components/UsernamePasswordListTile.vue [hunk 7]
```diff
@@ -15,50 +15,66 @@ limitations under the License.
 -->
 
 <template>
-  <div v-show="(!!username || !!email) && !!password">
-    <v-list-item v-if="username">
+  <div v-show="((!!username || !!email) && !!password) || showNotAvailablePlaceholder">
+    <template v-if="(!!username || !!email) && !!password">
```
Comment (holgerkoser) [inline frontend/src/components/UsernamePasswordListTile.vue:19]: The code became to complex for html template from my point of view. We should create a computed property `showCredentials` or something like this.

```suggestion
  <div v-show="showCredentials || showNotAvailablePlaceholder">
    <template v-if="showCredentials">
```

Comment (petersutter) [reply frontend/src/components/UsernamePasswordListTile.vue:19]: done

**Review by holgerkoser — APPROVED** [review]
/lgtm
