### PR TITLE
Bug/uncaught undefined

### LINKED ISSUE #623: On project creation: Uncaught (in promise) undefined
**What happened**:
```
Uncaught (in promise) undefined
eval @ vue-router.esm.js?8c4f:2051
abort @ vue-router.esm.js?8c4f:2082
iterator @ vue-router.esm.js?8c4f:2117
step @ vue-router.esm.js?8c4f:1846
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ index.js?d824:651
async function (async)
eval @ index.js?d824:649
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
confirmTransition @ vue-router.esm.js?8c4f:2147
transitionTo @ vue-router.esm.js?8c4f:2034
push @ vue-router.esm.js?8c4f:2365
eval @ vue-router.esm.js?8c4f:2779
push @ vue-router.esm.js?8c4f:2778
onProjectCreated @ Home.vue?76f2:88
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3882
submit @ ProjectDialog.vue?0b33:319
async function (async)
submit @ ProjectDialog.vue?0b33:315
click @ ProjectDialog.vue?7a05:330
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3882
click @ vuetify.js?ce5b:1387
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911

```
**What you expected to happen**:
no error in log when creating a project

**How to reproduce it (as minimally and precisely as possible)**:
- Make sure you are not assigned to any projects.
- Create your first project and check the browser console for errors

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
Fixes the error in the browser console that appears when creating your first project.
This happened because both in 
- `ProjectDialog.vue` https://github.com/gardener/dashboard/blob/85d37eb731bc40670f6bfe21cb34b16c673ade46/frontend/src/dialogs/ProjectDialog.vue#L318-L324 and 
- `Home.vue` https://github.com/gardener/dashboard/blob/85d37eb731bc40670f6bfe21cb34b16c673ade46/frontend/src/pages/Home.vue#L81-L90
 a navigation was initiated.

**Which issue(s) this PR fixes**:
Fixes #623 

**Special notes for your reviewer**:

**Release note**:

```improvement user

```

### CODE REVIEW

File: frontend/src/pages/Home.vue [hunk 1]
```diff
@@ -33,7 +33,7 @@ limitations under the License.
           <span>You are not authorized to create projects</span>
         </v-tooltip>
       </v-card-text>
-      <project-create-dialog @submit="onProjectCreated" v-model="projectDialog">
```
Comment (grolu) [inline frontend/src/pages/Home.vue]: let's review this in detail

Comment (holgerkoser) [reply frontend/src/pages/Home.vue]: agree
