### PR TITLE
Permanently hide alert banner

### LINKED ISSUE #887: Closing the Warning box it's not remembered
**What happened**:
I'm closing this alert box on every login, and still pops up.
image

**What you expected to happen**:
I would expect that my action is remembered, and no alert is shown next login

**How to reproduce it (as minimally and precisely as possible)**:
Login, and notice the Orange Alert on the top. Close the alert. Log out and Login again.
Alert will still be visible
**Anything else we need to know**:

**Environment**:
garden.canary.k8s.ondemand.com

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
This PR adds an option to hide the configured alert banner permanently.

- `GAlert` component will be renamed to `GMessage`
- A new component `GAlert` will be introduced that only displays the alert in case the message was not closed by the user

When configuring an alert as admin, you can now set an `identifier` for the message. This identifier will be used to identify which messages the user wants to hide permanently.
This gives you the ability to adapt the message text and use the same identifier without that the user needs to read and hide the message again.
On the other hand, you can force the display of the message by changing the identifier.

Example `values.yaml`

```yaml
frontendConfig:
  alert:
    type: error
    message: This is an **alert** banner
    # identifer: alert-identifier # Optional. If not set, a hash of the alert.message will be used as identifier. The identifier is used to store the user's decision to not show the alert message with this identifier again.
```

**Which issue(s) this PR fixes**:
Fixes #887

**Special notes for your reviewer**:

**Release note**:

```bugfix user
The alert banner is now permanently hidden when clicking the close icon
```

### CODE REVIEW

**Comment by grolu** [comment]
I'm a bit confused regarding the caption of the textbox. What does `do not ask me again` mean? From the code it looks like activating the checkbox permanently hides the message? In that case it should rather be labelled as `Permanently hide message`.

**Comment by petersutter** [comment]
Good point, I will change it as you suggested 👍

**Comment by petersutter** [comment]
After second thought, I changed the caption to „Hide Message“ as it is only permanently if you  select the checkbox

**Comment by grolu** [comment]
IDK ... I don't think it makes it clear. For me the checkbox still means that I don't want to see this confirmation popup again but I would never expect that this controls if the alert message is permanently hidden or not.

**Comment by petersutter** [comment]
As we discussed offline, I will remove the popup altogether and the alert will be permanently hidden when clicking on the close icon

File: frontend/src/components/GAlert.vue [hunk 1]
```diff
@@ -5,69 +5,101 @@ SPDX-License-Identifier: Apache-2.0
...
+      const permanentlyHiddenIds = this.$localStorage.getObject(LOCAL_STORE_ALERT_BANNER_HIDDEN_MESSAGES) || {}
+      return permanentlyHiddenIds[this.identifier] === true
+    },
+    updateAlertVisibility () {
+      const visible = !this.isPermanentlyHidden(this.identifier)
+      this.setAlertVisibility(visible)
+    },
+    setAlertVisibility (visible) {
+      this.alertVisible = visible
+      this.$emit('value', visible)
```
Comment (holgerkoser) [inline frontend/src/components/GAlert.vue:87]: Why do we emit visibility?
Why is the name value? Shouldn't it be a value prop with two ways data binding and emit `input`?

File: frontend/src/components/GMessage.vue [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+    }
+  },
+  computed: {
+    alertVisible: {
+      get () {
+        return !!this.message
+      },
+      set (value) {
+        if (!value) {
+          this.$emit('update:message', undefined)
```
Comment (holgerkoser) [inline frontend/src/components/GMessage.vue:56]: I think the message prop does not change only the visiblility?

File: frontend/src/components/dialogs/GDialog.vue [hunk 3]
```diff
@@ -22,7 +22,7 @@ SPDX-License-Identifier: Apache-2.0
         <slot name="message">
           This is a generic dialog template.
         </slot>
-        <g-alert color="error" class="mt-4" :message.sync="message" :detailedMessage.sync="detailedMessage"></g-alert>
+        <g-message color="error" class="mt-4" :message.sync="message" :detailedMessage.sync="detailedMessage"></g-message>
```
Comment (holgerkoser) [inline frontend/src/components/dialogs/GDialog.vue:25]: I cannot understand why message and detailedMessage are sync properties?

File: frontend/src/components/GAlert.vue [hunk 4]
```diff
@@ -5,69 +5,101 @@ SPDX-License-Identifier: Apache-2.0
...
+    ]),
+    async closeBanner () {
+      if (this.identifier) { // hide permanently
+        this.hidePermanently(this.identifier)
       }
+
+      this.setAlertVisibility(false)
+    },
+    hidePermanently (identifier) {
+      const permanentlyHiddenIds = this.$localStorage.getObject(LOCAL_STORE_ALERT_BANNER_HIDDEN_MESSAGES) || {}
```
Comment (holgerkoser) [inline frontend/src/components/GAlert.vue:69]: Why don't we write these values into the vuex store and decide there centrally (via localStorage plugin) what to persist in localStroage. I think this would be much cleaner.

Comment (holgerkoser) [reply frontend/src/components/GAlert.vue:69]:
```js
import debounce from 'lodash/debounce'

const ALERT_BANNER_HIDDEN_MESSAGES = 'global/alert-banner/hidden-messages'
const SET_ALERT_BANNER_HIDDEN_MESSAGES = 'SET_ALERT_BANNER_HIDDEN_MESSAGES'


const setAlertBannerHiddenMessages = debounce(value => {
  localStorage.setItem(ALERT_BANNER_HIDDEN_MESSAGES, JSON.stringify(value))
}, 200)

const LocalStoragePlugin= store => {
  const value = localStorage.getItem(ALERT_BANNER_HIDDEN_MESSAGES)
  if (value) {
    store.commit(SET_ALERT_BANNER_HIDDEN_MESSAGES, JSON.parse(value))
  }
  store.subscribe((mutation, state) => {
    switch (mutation.type) {
      case SET_ALERT_BANNER_HIDDEN_MESSAGES: 
        setAlertBannerHiddenMessages(mutation.payload)
        break
    }
  })
}

const store = new Vuex.Store({
  state,
  getters,
  actions,
  mutations,
  plugins: [LocalStoragePlugin]
})
```

Comment (holgerkoser) [reply frontend/src/components/GAlert.vue:69]: Let's create a separate ticket for this.

File: frontend/src/components/GAlert.vue (hunk 1 above)
Comment (holgerkoser) [reply frontend/src/components/GAlert.vue:87]: Either add a value (v-model) property and emit input or just emit input with value prop.

File: frontend/src/store/index.js [hunk 5]
```diff
@@ -849,17 +849,24 @@ const getters = {
     const user = state.user
     return user ? user.name || fullDisplayName(user.id) : ''
   },
-  alertMessage (state) {
```
Comment (holgerkoser) [inline frontend/src/store/index.js:852]: This is needed. Do not remove.

File: frontend/src/components/GAlert.vue (hunk 4 above)
Comment (petersutter) [reply frontend/src/components/GAlert.vue:69]: https://github.com/gardener/dashboard/issues/905

File: frontend/src/components/GAlert.vue (hunk 1 above)
Comment (petersutter) [reply frontend/src/components/GAlert.vue:87]: I removed the emit completely. The component handles the visibility which depends if the user already dismissed the message already or not

File: frontend/src/components/dialogs/GDialog.vue (hunk 3 above)
Comment (petersutter) [reply frontend/src/components/dialogs/GDialog.vue:25]: as discussed offline we will not start this refactoring in this pr

File: frontend/src/store/index.js (hunk 5 above)
Comment (petersutter) [reply frontend/src/store/index.js]: ✅

File: frontend/src/components/GMessage.vue (hunk 2 above)
Comment (petersutter) [reply frontend/src/components/GMessage.vue:56]: see https://github.com/gardener/dashboard/pull/899#discussion_r544370302

File: frontend/src/store/index.js (hunk 5 above)
Comment (petersutter) [reply frontend/src/store/index.js]: ✅

**Review by holgerkoser — APPROVED** [review]
/lgtm
