### PR TITLE
fixed isShootLastOperationTypeControlPlaneMigrating logic

### LINKED ISSUE #1098: Successful CP migration is shown as operation in progress with reason `Creating resources on new Seed`
/kind bug

**What happened**:
Successful CP migration is shown as operation in progress with reason `Creating resources on new Seed`

**What you expected to happen**:
The dashboard to do not show operation in progress after successful CP migration.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot
2. Perform CP migration

3. Make sure that after the CP migration the Shoot status looks like (only relevant fields are shown):

```yaml
status:
  lastOperation:
    lastUpdateTime: '2021-09-14T06:27:05Z'
    progress: 100
    state: Succeeded
    type: Restore
```

4. Make sure that the dashboard still shows progress bar with reason `Creating resources on new Seed`

Screenshot 2021-09-14 at 9 49 34

**Environment**:
Dashboard version: 1.52.0

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1098

**Special notes for your reviewer**:

**Release note**:

```bugfix user
NONE
```

### CODE REVIEW

File: frontend/src/mixins/shootItem.js [hunk 1]
```diff
@@ -165,7 +165,7 @@ export const shootItem = {
       return isTypeDelete(this.shootLastOperation)
     },
     isShootLastOperationTypeControlPlaneMigrating () {
-      return this.shootLastOperation.type === 'Migrate' || this.shootLastOperation.type === 'Restore'
+      return this.shootLastOperation.type === 'Migrate' || (this.shootLastOperation.type === 'Restore' && this.shootLastOperation.type !== 'Succeeded')
```
Comment (holgerkoser) [inline frontend/src/mixins/shootItem.js:168]:
```suggestion
      return this.shootLastOperation.type === 'Migrate' || (this.shootLastOperation.type === 'Restore' && this.shootLastOperation.state !== 'Succeeded')
```

**Review by holgerkoser — APPROVED** [review]
/lgtm
