### PR TITLE
Force Delete Cluster

### LINKED ISSUE #1607: Forcefully delete shoot cluster
**What would you like to be added**:
Show option to forcefully delete shoot cluster that is in error state.

***Ideas***
- We could add a button next to the status icon (like the retry button) that only shows up for deleted clusters that are in delete failed. 
- User needs to confirm resource cleanup (e.g. by checkbox)
- Show warning (see gardener issue)

**Why is this needed**:
Gardener added this feature with this PR: https://github.com/gardener/gardener/pull/8414

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:

Screenshot 2024-02-01 at 12 48 35

Screenshot 2024-02-02 at 18 39 58

Screenshot 2024-02-01 at 13 41 43

**Which issue(s) this PR fixes**:
Fixes #1607

**Special notes for your reviewer**:

**Release note**:

```feature user
Implemented Force Deletion of Clusters
If a cluster is stuck in deletion, users can force delete clusters via the dashboard. This is only possible when the `ShootForceDeletion` featuregate in the apiserver is turned on
```

```bugfix user
Fixed an issue that caused `dark` theme color to be applied to some alert messages
```

```feature user
Improved cluster messages
- Show icons always next to title on cluster details page
- Fixed overall severity sometimes not correct
```

### CODE REVIEW

File: frontend/src/components/GForceDeletion.vue [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+          color="warning"
+          class="mr-1"
+        >
+          mdi-alert-box
+        </v-icon>
+        <span>The cluster will not be deleted as long as reconciliation is deactivated.</span>
+      </v-row>
+    </p>
+  </g-shoot-action-dialog>
+  <g-shoot-action-button
```
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/components/GForceDeletion.vue:58]: I'm also not sure if this can happen. And I think I also tested this... maybe only on the details page. I will add a `d-flex` div to ensure the layout does not break.

File: frontend/src/components/GCountdownCheckbox.vue [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+  <div
+    class="d-flex"
+  >
+    <div class="mr-3 d-flex align-center checkbox-div">
+      <v-checkbox
+        v-if="!isCountdownActive"
+        v-model="internalValue"
+        hide-details
+      />
+      <v-progress-circular
```
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/components/GCountdownCheckbox.vue:17]: Yes. I'm also not sure if we want to have something like that at all. The countdown is configurable, so we could increase the waiting time or disable it. We could also make it configurable and / or dependent on the user type (isAdmin). I think it is good to have this checkbox to explicitly confirm the alert though. Let's discuss this in a sync.

File: frontend/src/components/GForceDeletion.vue [hunk 3]
```diff
@@ -0,0 +1,185 @@
...
+      This action cannot be undone.
+    </p>
+    <g-expand-transition-group>
+      <v-alert
+        v-if="!confirmed"
+        type="warning"
+      >
+        You <span class="font-weight-bold">MUST</span> ensure that all the resources created in the IaaS account are cleaned
+        up to prevent orphaned resources. Gardener will <span class="font-weight-bold">NOT</span> delete any resources in the underlying infrastructure account.
+        Hence, use this feature at your own risk and only if you are fully aware of these consequences.
```
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/components/GForceDeletion.vue:40]: We could link to the official documentation: https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#force-deletion

But basically I copied the text from there and there is not much additional information.

File: frontend/src/components/GForceDeletion.vue [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+    </p>
+    <p class="my-2 text-error font-weight-bold">
+      This action cannot be undone.
+    </p>
+    <g-expand-transition-group>
+      <v-alert
+        v-if="!confirmed"
+        type="warning"
+      >
+        You <span class="font-weight-bold">MUST</span> ensure that all the resources created in the IaaS account are cleaned
```
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/components/GForceDeletion.vue:38]: done

File: frontend/src/components/ShootDetails/GShootLifecycleCard.vue [hunk 5]
```diff
@@ -141,14 +138,38 @@ SPDX-License-Identifier: Apache-2.0
           </template>
           <g-list-item-content>
             Delete Cluster
+            <template
+              v-if="canForceDeleteShoot"
+              #description
+            >
+              <div class="d-flex">
+                <v-icon
```
Comment (petersutter) [inline frontend/src/components/ShootDetails/GShootLifecycleCard.vue:146]: Screenshot 2024-01-25 at 11 04 37
I think we should do it similar like for the last maintenance status to be more consistent

File: frontend/src/components/GForceDeleteCluster.vue [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+        :size="22"
+      />
+    </v-list-item-title>
+  </v-list>
+  <p>
+    Type <span class="font-weight-bold">{{ shootName }}</span> below to confirm the forceful deletion of the cluster.
+  </p>
+  <g-expand-transition-group>
+    <v-alert
+      v-if="!confirmed"
```
Comment (petersutter) [inline frontend/src/components/GForceDeleteCluster.vue:23]: the alert should not disappear, as the checkbox is referring to the text above which then disappears

File: frontend/src/components/GForceDeleteCluster.vue [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+    </v-list-item-subtitle>
+    <v-list-item-title>
+      <g-account-avatar
+        :account-name="shootCreatedBy"
+        :size="22"
+      />
+    </v-list-item-title>
+  </v-list>
+  <p>
+    Type <span class="font-weight-bold">{{ shootName }}</span> below to confirm the forceful deletion of the cluster.
```
Comment (petersutter) [inline frontend/src/components/GForceDeleteCluster.vue:19]:
```suggestion
    Type <span class="font-weight-bold">{{ shootName }}</span> below and confirm that you are aware of the side effects and the necessary actions you must take in order to proceed with the forceful deletion of the cluster.
```

File: frontend/src/components/GCountdownCheckbox.vue (hunk 2 above)
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/components/GCountdownCheckbox.vue]: removed

File: frontend/src/components/GForceDeleteCluster.vue [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+      type="warning"
+      variant="tonal"
+    >
+      You <span class="font-weight-bold">MUST</span> ensure that all the resources created in the IaaS account
+      <code>
+        <g-shoot-secret-name
+          :namespace="shootNamespace"
+          :secret-binding-name="shootSecretBindingName"
+        />
+      </code>
```
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/components/GForceDeleteCluster.vue:34]: OK - I'll add a tooltip. We could also remove the secret where we don't need it. I think we want to have it on the details page. But I think it also doesn't hurt to have the link

File: frontend/__tests__/utils/shootItem.spec.js [hunk 9]
```diff
@@ -0,0 +1,270 @@
...
+    wrapper = shallowMount(Component, {
+      propsData: {
+        shootItem: shootResource,
+      },
+    })
+  }
+
+  beforeEach(() => {
+    setActivePinia(createPinia())
+    mountMixinWithShootResource({})
```
Comment (holgerkoser) [inline frontend/__tests__/utils/shootItem.spec.js:37]: Do not mount the component in beforeEach.

File: frontend/src/components/GForceDeleteCluster.vue [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+      Created By
+    </v-list-item-subtitle>
+    <v-list-item-title>
+      <g-account-avatar
+        :account-name="shootCreatedBy"
+        :size="22"
+      />
+    </v-list-item-title>
+  </v-list>
+  <p>
```
Comment (holgerkoser) [inline frontend/src/components/GForceDeleteCluster.vue:18]: I would not use `<p>` in a layout. Use `<div>` instead.

File: frontend/src/components/GForceDeleteCluster.vue [hunk 11]
```diff
@@ -0,0 +1,119 @@
+<!--
+SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
+
+SPDX-License-Identifier: Apache-2.0
+-->
+<template>
+  <v-list>
```
Comment (holgerkoser) [inline frontend/src/components/GForceDeleteCluster.vue:7]: Why do we use a list here?

File: frontend/src/components/GForceDeleteCluster.vue [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+          <g-shoot-secret-name
+            :namespace="shootNamespace"
+            :secret-binding-name="shootSecretBindingName"
+          />
+        </code>
+      </span>
+    </template>
+  </v-checkbox>
+  <p v-if="isShootReconciliationDeactivated">
+    <v-row class="fill-height">
```
Comment (holgerkoser) [inline frontend/src/components/GForceDeleteCluster.vue:63]: Replace `<p>` and `<v-row>` with `<div>`'s

File: frontend/src/components/GForceDeleteCluster.vue [hunk 13]
```diff
@@ -0,0 +1,119 @@
...
+    return {
+      confirmed: false,
+    }
+  },
+}
+</script>
+
+<style lang="scss" scoped>
+p {
+  margin-bottom: 0
```
Comment (holgerkoser) [inline frontend/src/components/GForceDeleteCluster.vue:117]: Use mb-0 instead

File: frontend/src/components/GShootActionForceDelete.vue [hunk 14]
```diff
@@ -0,0 +1,97 @@
...
+      default: false,
+    },
+  },
+  computed: {
+    caption () {
+      return this.isShootMarkedForForceDeletion
+        ? 'Cluster already marked for force deletion'
+        : this.isShootMarkedForDeletion
+          ? 'Cluster already marked for deletion'
+          : this.buttonTitle
```
Comment (holgerkoser) [inline frontend/src/components/GShootActionForceDelete.vue:62]:
```suggestion
      if (this.isShootMarkedForForceDeletion) {
        return 'Cluster already marked for force deletion'
      }
      return this.isShootMarkedForDeletion
        ? 'Cluster already marked for deletion'
        : this.buttonTitle
```

File: frontend/src/components/GShootSecretName.vue [hunk 15]
```diff
@@ -0,0 +1,72 @@
+<!--
+SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
+
+SPDX-License-Identifier: Apache-2.0
+-->
+
+<template>
+  <span>
```
Comment (holgerkoser) [inline frontend/src/components/GShootSecretName.vue:8]: Never wrap div in a span. Remove span or use div

File: frontend/src/components/GShootSecretName.vue [hunk 16]
```diff
@@ -0,0 +1,72 @@
...
+    <g-text-router-link
+      v-if="canLinkToSecret"
+      :to="{ name: 'Secret', params: { name: secretBindingName, namespace: namespace } }"
+      :text="secretBindingName"
+    />
+    <span v-else>{{ secretBindingName }}</span>
+    <v-tooltip
+      v-if="secret"
+      location="top"
+      activator="parent"
```
Comment (holgerkoser) [inline frontend/src/components/GShootSecretName.vue:18]: Why not use the activator slot here?

File: frontend/src/components/GShootStatus.vue [hunk 17]
```diff
@@ -235,6 +235,7 @@ export default {
   data () {
     return {
       retryingOperation: false,
+      forceDeleteClusterDialog: false,
```
Comment (holgerkoser) [inline frontend/src/components/GShootStatus.vue:238]: This property is never used

File: frontend/src/mixins/shootItem.js [hunk 18]
```diff
@@ -267,6 +284,25 @@ export const shootItem = {
...
+    canForceDeleteShoot () {
+      if (!this.isShootForceDeletionEnabled) {
+        return false
+      }
+      if (!this.shootDeletionTimestamp) {
+        return false
+      }
+
+      const shootErrorCodes = errorCodesFromArray(this.shootLastErrors)
+      const forceDeleteErrorCodes = [
```
Comment (holgerkoser) [inline frontend/src/mixins/shootItem.js:296]: Move outside of function

File: frontend/src/mixins/shootItem.js [hunk 19]
```diff
@@ -267,6 +284,25 @@ export const shootItem = {
...
+        'ERR_CLEANUP_CLUSTER_RESOURCES',
+        'ERR_CONFIGURATION_PROBLEM',
+        'ERR_INFRA_DEPENDENCIES',
+        'ERR_INFRA_UNAUTHENTICATED',
+        'ERR_INFRA_UNAUTHORIZED',
+      ]
+      const shootHasForceDeleteError = shootErrorCodes.some(item => forceDeleteErrorCodes.includes(item))
+      return shootHasForceDeleteError
```
Comment (holgerkoser) [inline frontend/src/mixins/shootItem.js:304]:
```suggestion
      return shootErrorCodes.some(item => forceDeleteErrorCodes.includes(item))
```

File: frontend/__tests__/mixins/shootItem.spec.js [hunk 20]
```diff
@@ -0,0 +1,280 @@
...
+      })
+      const shootStore = useShootStore(pinia)
+      shootStore.isShootActive = () => {
+        return true
+      }
+      const wrapper = shallowMount(Component, {
+        propsData: {
+          shootItem: {},
+        },
+      })
```
Comment (holgerkoser) [inline frontend/__tests__/mixins/shootItem.spec.js:246]:
```suggestion
      const shootItem = {
        metadata: {
          uid: '42',
        },
      }
      const pinia = createTestingPinia()
      const shootStore = useShootStore(pinia)
      shootStore.isShootActive.mockImplementationOnce(uid => uid === shootItem.metadata.uid)
      const wrapper = shallowMount(Component, {
        props: {
          shootItem,
        },
        global: {
          plugins: [pinia],
        },
      })
```

File: frontend/__tests__/mixins/shootItem.spec.js [hunk 21]
```diff
@@ -0,0 +1,280 @@
...
+        stubActions: false,
+      })
+      const configStore = useConfigStore(pinia)
+      configStore.features = {
+        shootForceDeletionEnabled: true,
+      }
+      const wrapper = shallowMount(Component, {
+        propsData: {
+          shootItem,
+        },
```
Comment (holgerkoser) [inline frontend/__tests__/mixins/shootItem.spec.js:274]:
```suggestion
        },
        global: {
          plugins: [pinia],
        },
```

File: frontend/src/components/ShootDetails/GShootLifecycleCard.vue [hunk 22]
```diff
@@ -138,13 +129,38 @@ SPDX-License-Identifier: Apache-2.0
...
+            </template>
           </g-list-item-content>
           <template #append>
             <g-shoot-action-delete-cluster
+              v-if="!canForceDeleteShoot"
               v-model="deleteClusterDialog"
               :shoot-item="shootItem"
             />
+            <g-shoot-action-force-delete
+              v-if="canForceDeleteShoot"
```
Comment (holgerkoser) [inline frontend/src/components/ShootDetails/GShootLifecycleCard.vue:158]:
```suggestion
              v-else
```

File: frontend/src/components/ShootDetails/GShootLifecycleCard.vue [hunk 23]
```diff
@@ -138,13 +129,38 @@ SPDX-License-Identifier: Apache-2.0
...
+              v-model="forceDeleteDialog"
+              :shoot-item="shootItem"
+              dialog
```
Comment (holgerkoser) [inline frontend/src/components/ShootDetails/GShootLifecycleCard.vue:161]:
```suggestion
```

File: frontend/src/components/GShootListRowActions.vue [hunk 24]
```diff
@@ -52,14 +52,21 @@ SPDX-License-Identifier: Apache-2.0
...
           v-model="deleteClusterDialog"
           :shoot-item="shootItem"
           text
         />
       </v-list-item>
+      <v-list-item v-if="canForceDeleteShoot">
+        <g-shoot-action-force-delete
+          v-model="forceDeleteDialog"
+          :shoot-item="shootItem"
+          button
```
Comment (holgerkoser) [inline frontend/src/components/GShootListRowActions.vue:66]: do we need this??

File: frontend/src/components/ShootDetails/GShootLifecycleCard.vue [hunk 25]
```diff
@@ -138,13 +129,38 @@ SPDX-License-Identifier: Apache-2.0
...
+              button
```
Comment (holgerkoser) [inline frontend/src/components/ShootDetails/GShootLifecycleCard.vue:162]:
```suggestion
```

File: frontend/src/components/ShootMessages/GShootMessages.vue [hunk 26]
```diff
@@ -356,12 +361,9 @@ export default {
...
     },
     overallSeverity () {
-      for (const { severity } of this.shootMessages) {
-        if (['error', 'warning', 'verbose'].includes(severity)) {
-          return severity
-        }
-      }
-      return 'info'
+      const severityOrder = { error: 1, warning: 2, info: 3, verbose: 4 }
+      const sortedMessages = orderBy(this.shootMessages, [message => severityOrder[message.severity]], ['asc'])
```
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/components/ShootMessages/GShootMessages.vue:365]: do you have a better idea other tha doing something like this:

```js
let highestSeverity = 'verbose'; // Start with the lowest severity
const severityOrder = ['error', 'warning', 'info', 'verbose'];

  for (const { severity } of this.shootMessages) {
    // Check if the current severity is higher than the highestSeverity found so far
    if (severityOrder.indexOf(severity) < severityOrder.indexOf(highestSeverity)) {
      highestSeverity = severity;
    }
  }
  return highestSeverity;
```

ChatGPT 4 did also come up with a better solution

File: frontend/src/mixins/shootItem.js [hunk 27]
```diff
@@ -317,11 +317,12 @@ export const shootItem = {
     ...mapActions(useProjectStore, [
       'projectNameByNamespace',
     ]),
-    shootActionToolTip (tooltip) {
+    shootActionToolTip (tooltip, overrideDeletionFlag) {
```
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/mixins/shootItem.js:320]: ok I also thought about doing that since it is only used in two places after the recent refactoring. If you also consider this to be the way to go I will do this

File: frontend/src/components/GShootListRowActions.vue (hunk 24 above)
Comment (grolu) [reply frontend/src/components/GShootListRowActions.vue:66]: no not since the recent refactoring. did slip in on merging

File: frontend/src/components/ShootMessages/GShootMessages.vue (hunk 26 above)
[the remark this answers is not in the document]
Comment (holgerkoser) [reply frontend/src/components/ShootMessages/GShootMessages.vue:365]: oder halt so higher ==> größerer index! 
```js
  const severityIndex = { none: 0, verbose: 1, info: 2, warning: 3, error: 4 }
  let maxSeverity = 'none'
  for (const { severity = 'none' } of this.shootMessages) {
    if (severityIndex[severity] > severityIndex[maxSeverity]) {
      maxSeverity = severity
    }
  }
  return maxSeverity !== 'none' 
    ? maxSeverity 
    : 'info'
```

File: frontend/src/components/ShootVersion/GShootVersion.vue [hunk 28]
```diff
@@ -234,6 +234,17 @@ export default {
 
       this.$refs.shootVersionUpdate.reset()
     },
+    shootActionToolTip(tooltip, overrideDeletionFlag) {
+      if (this.isShootActionsDisabledForPurpose) {
+        return 'Cluster update disabled for clusters with purpose infrastructure'
```
Comment (holgerkoser) [inline frontend/src/components/ShootVersion/GShootVersion.vue:239]:
```suggestion
        return 'Version update disabled for clusters with purpose "infrastructure"'
```

File: frontend/src/components/ShootVersion/GShootVersion.vue [hunk 29]
```diff
@@ -234,6 +234,17 @@ export default {
...
+      }
+
+      if (this.isShootMarkedForDeletion) {
+        return 'Cluster update disabled for clusters that are marked for deletion'
```
Comment (holgerkoser) [inline frontend/src/components/ShootVersion/GShootVersion.vue:243]:
```suggestion
        return 'Version update disabled for clusters that are marked for deletion'
```

File: frontend/src/components/dialogs/GActionButtonDialog.vue [hunk 30]
```diff
@@ -172,6 +172,17 @@ export default {
         this.$refs.gDialog.hideDialog()
       }
     },
+    shootActionToolTip(tooltip) {
+      if (this.isShootActionsDisabledForPurpose) {
+        return 'Actions disabled for clusters with purpose infrastructure'
```
Comment (holgerkoser) [inline frontend/src/components/dialogs/GActionButtonDialog.vue:177]:
```suggestion
        return 'Actions disabled for clusters with purpose "infrastructure"'
```

File: frontend/src/components/dialogs/GActionButtonDialog.vue [hunk 31]
```diff
@@ -172,6 +172,17 @@ export default {
         this.$refs.gDialog.hideDialog()
       }
     },
+    shootActionToolTip(tooltip) {
```
Comment (holgerkoser) [inline frontend/src/components/dialogs/GActionButtonDialog.vue:175]:
```suggestion
    shootActionToolTip (tooltip) {
```

File: frontend/src/components/ShootVersion/GShootVersion.vue [hunk 32]
```diff
@@ -234,6 +234,17 @@ export default {
 
       this.$refs.shootVersionUpdate.reset()
     },
+    shootActionToolTip(tooltip, overrideDeletionFlag) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootVersion/GShootVersion.vue:237]:
```suggestion
    shootActionToolTip (tooltip, overrideDeletionFlag) {
```

**Review by petersutter — APPROVED** [review]
/lgtm

File: frontend/src/components/GForceDeleteCluster.vue [hunk 33]
```diff
@@ -0,0 +1,123 @@
...
+    />
+  </div>
+  <div class="mt-2">
+    Type <span class="font-weight-bold">{{ shootName }}</span> below and confirm that you are aware of the side effects and the necessary actions you must take in order to proceed with the forceful deletion of the cluster.
+  </div>
+  <div class="mb-2 font-weight-bold">
+    This action cannot be undone.
+  </div>
+  <v-alert
+    class="my-2 disc-list"
```
Comment (grolu) [inline frontend/src/components/GForceDeleteCluster.vue:22]:
```suggestion
    class="my-2"
```

**Review by holgerkoser — APPROVED** [review]
/lgtm
