### PR TITLE
Maintenance Dialog Improvements and Fixes

### LINKED ISSUE #1496: Add UTC time to maintenance schedule
**What would you like to be added**:
The maintenance schedule is presently set with a timezone. However, many other things in the cluster (eg. monitoring) is based on UTC time. It would be useful to add the automatically converted UTC time next to the time. Something like:
image

**Why is this needed**:
Would make it easier/simpler/faster to know UTC time when troubleshooting (not having to convert).

### LINKED ISSUE #1574: Maintenance Time Window resets on save
**What happened**:
When you open the maintenance configuration dialog, the maintenance start time resets to a default value. When the user presses the save button the maintenance window changes which sometimes results in an error.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:
- Fixes some issues with maintenance Dialog #1574
- Added maintenance time window configuration
- Improved hints (added UTC time) #1496

Screenshot 2023-09-26 at 13 49 48

**Which issue(s) this PR fixes**:
Fixes #1574
Fixes #1496

**Special notes for your reviewer**:

**Release note**:

```feature user
Added an input field to configure the maintenance time window duration. The textfield hints now show the UTC begin and end time
```

### CODE REVIEW

File: frontend/src/components/ShootMaintenance/GMaintenanceTime.vue [hunk 1]
```diff
@@ -121,50 +160,52 @@ export default {
...
+    setBeginTimeAndTimezone (windowBegin) {
       const beginTime = new TimeWithOffset(windowBegin)
       if (!beginTime.isValid()) {
         return undefined
       }
       this.maintenanceBegin = beginTime.getTimeString()
       this.maintenanceTimezone = beginTime.getTimezoneString()
     },
-    setEndTimeTimezoneString (windowEnd) {
+    setWindowDurationByWindowEnd (windowEnd) {
```
Comment (petersutter) [inline frontend/src/components/ShootMaintenance/GMaintenanceTime.vue:182]: omit `ByWindowEnd` from the function name

**Review by petersutter — APPROVED** [review]
/lgtm

File: frontend/src/utils/index.js [hunk 2]
```diff
@@ -539,6 +539,19 @@ export function maintenanceWindowWithBeginAndTimezone (beginTime, beginTimezone,
...
+  if (!beginMoment.isValid() || !endMoment.isValid()) {
+    return undefined
+  }
+  if (endMoment.isBefore(beginMoment)) {
+    endMoment = endMoment.add(1, 'day')
+  }
+
+  return endMoment.diff(beginMoment, 'minutes')
+}
+
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:554]: This function is not releated to maintance and windows. I calculates the differnence in minutes for two times in the 24h format.

Comment (grolu) [reply frontend/src/utils/index.js:554]: renamed to getDurationInMinutes

File: frontend/src/views/GNewShoot.vue [hunk 3]
```diff
@@ -512,8 +512,8 @@ export default {
       const end = get(shootResource, 'spec.maintenance.timeWindow.end')
       const k8sUpdates = get(shootResource, 'spec.maintenance.autoUpdate.kubernetesVersion', true)
       const osUpdates = get(shootResource, 'spec.maintenance.autoUpdate.machineImageVersion', true)
-      this.$refs.maintenanceTime.setBeginTimeTimezoneString(begin)
-      this.$refs.maintenanceTime.setEndTimeTimezoneString(end)
+      this.$refs.maintenanceTime.setBeginTimeAndTimezone(begin)
+      this.$refs.maintenanceTime.setWindowDuration(end)
```
Comment (holgerkoser) [inline frontend/src/views/GNewShoot.vue:516]:
```suggestion
      this.$refs.maintenanceTime.setMaintenanceWindow(begin, end)
```

I think we should have one method 'setMaintenanceWindow' that changes the maintenance window. This would also make clear what is does when called from outside, I think. The implementation could look like:
```js
    reset () {
      this.setMaintenanceWindow(this.timeWindowBegin, this.timeWindowEnd)
    },
    ...
    setMaintenanceWindow (begin, end) {
      const defaultDuration = 60
      if (begin && end) {
        const beginTime = new TimeWithOffset(begin)
        if (beginTime.isValid()) {
          this.maintenanceBegin = beginTime.getTimeString()
          this.maintenanceTimezone = beginTime.getTimezoneString()
        }
        const endTime = new TimeWithOffset(end)
        if (endTime.isValid()) {
          const duration = getDurationInMinutes(this.maintenanceBegin, endTime.getTimeString())
          this.windowDuration = duration > 0 ? duration : defaultDuration
        }
      } else {
        this.maintenanceBegin = randomMaintenanceBegin()
        this.maintenanceTimezone = this.timezone
        this.windowDuration = defaultDuration
      }
    },
    ...
```

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Review by petersutter — APPROVED** [review]
/lgtm
