### PR TITLE
Properly handle navigation between projects

### LINKED ISSUE #326: Navigation fails with "Failed to fetch shoot"
#####  Version the issue has been seen with
1.28.0

##### Expected behaviour you didn't see
Dashboard to handle properly the navigation between projects - when new project is selected, the shoots from the newly selected project to be listed.

##### Unexpected behaviour you saw
Dashboard fails with `Failed to fetch shoot`.

##### Steps to reproduce:
1. Open the dashboard.
2. Select a project from the sidebar. 
Ensure that after the selection the url is `<host>/namespace/<project-name>/shoots/` and all shoots in the project are listed.
3. Select a shoot. 
Ensure that after the selection the url is `<host>/namespace/<project-name>/shoots/<shoot-name>` and the shoot details are listed.
4. Select another project from the sidebar.
Ensure that the url changes to `<host>/namespace/<new-project-name>/shoots/<shoot-name>`, the dashboard searches for the same `shoot-name` in the newly selected project. And this all result in `Failed to fetch shoot` error.

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
The dashboard does not properly handle the navigation between projects in case e.g. the cluster details page is shown  - when the new project is selected, the clusters from the newly selected project should to be listed. See #324 for more details.

**Which issue(s) this PR fixes**:
Fixes #326

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fixed navigation between projects when showing cluster details. You are now redirected to the cluster list of the newly selected project.
```

### CODE REVIEW

File: frontend/src/router/index.js [hunk 1]
```diff
@@ -426,13 +445,18 @@ export default function createRouter ({ store, userManager }) {
...
-          case 'ShootItemEditor':
             return Promise
               .all([
                 store.dispatch('subscribeShoot', { name: params.name, namespace }),
                 store.dispatch('subscribeComments', { name: params.name, namespace })
               ])
               .then(() => undefined)
+          case 'ShootItemEditor':
+            return Promise
+              .all([
```
Comment (grolu) [inline frontend/src/router/index.js]: rm promise.all as only one call

Comment (petersutter) [reply frontend/src/router/index.js]: done

File: frontend/src/utils/index.js [hunk 2]
```diff
@@ -160,12 +160,15 @@ export function routes (router, includeRoutesWithProjectScope) {
   return filter(defaultRoute.children, hasMenu)
 }
 
-export function namespacedRoute (route, namespace) {
-  const name = routeName(route)
+export function namespacedRoute (route, namespace, name = undefined) {
```
Comment (grolu) [inline frontend/src/utils/index.js]: where do we use the name parameter

Comment (petersutter) [reply frontend/src/utils/index.js]: not used (yet), slipped in from webterm branch. I have removed it
