### PR TITLE
Reset filter on Secrets, Members and Shoot list page

### LINKED ISSUE #1524: Filter value does not reset when navigating
**What happened**:
When navigating to a different project, the search / filter value does not reset. If the target project has less data the filter input text field might even not be displayed even though the filter value is still applied.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Navigate to member page
- Select project with more than 3 members
- Search for a member
- Change to project with 3 members or less
- Filter input text field is hidden, filter value is still applied
- Reload page, filter value gets resetted

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
Reset filter on Secrets, Members and Shoot list page when switching the Project

**Which issue(s) this PR fixes**:
Fixes #1524

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Fixed an issue where the filter on the `Secrets`, `Members` and `Clusters` page was not reset when switching the Project
```

### CODE REVIEW

**Comment by grolu** [comment]
What about the shoot list filter? When I switch the project, the filter value remains in the search field, however the value is no longer applied (list is not filtered). I think we should reset the filter value in this case, too.

**Comment by petersutter** [comment]
right @grolu, fixed it

**Review by grolu — APPROVED** [review]
/lgtm

File: frontend/src/views/GMembers.vue [hunk 1]
```diff
@@ -555,6 +556,17 @@ const visibleServiceAccountTableHeaders = computed(() => {
   return filter(serviceAccountTableHeaders.value, ['selected', true])
 })
 
+watch(namespace, () => {
```
Comment (holgerkoser) [inline frontend/src/views/GMembers.vue:559]: Not directly related to this PR but the `namespace` should be imported from the `authzStore`.

File: frontend/src/views/GSecrets.vue [hunk 2]
```diff
@@ -327,12 +327,14 @@ export default {
...
-        'dnsSecretList',
-      ]),
-    ...mapGetters(useAuthzStore, ['canCreateSecrets']),
+    ...mapGetters(useSecretStore, [
+      'infrastructureSecretList',
+      'dnsSecretList',
+    ]),
+    ...mapGetters(useAuthzStore, [
+      'canCreateSecrets',
+      'namespace',
```
Comment (holgerkoser) [inline frontend/src/views/GSecrets.vue:336]:
```suggestion
      'namespace',
      'canCreateSecrets',
```

File: frontend/src/views/GShootList.vue [hunk 3]
```diff
@@ -281,20 +282,21 @@ export default {
...
     this.cachedItems = this.shootList.slice(0)
-    this.shootSearch = null
+    this.resetShootSearch()
     this.focusModeInternal = false
     next()
   },
   data () {
     return {
       shootSearch: '',
+      delayedShootSearch: '',
```
Comment (holgerkoser) [inline frontend/src/views/GShootList.vue:299]: Why do we need two properties? If we need it the name should be `debouncedShootSearch` to make it more clear what is is.

File: frontend/src/views/GShootList.vue [hunk 4]
```diff
@@ -73,6 +73,7 @@ SPDX-License-Identifier: Apache-2.0
             <template #activator="{ props }">
               <v-text-field
                 v-bind="props"
+                v-model="shootSearch"
```
Comment (holgerkoser) [inline frontend/src/views/GShootList.vue:76]: Do not use `v-model` and `@update:model-value` in combination

File: frontend/src/views/GSecrets.vue (hunk 2 above)
Comment (petersutter) [reply frontend/src/views/GSecrets.vue:336]: what is this change about?

Comment (petersutter) [reply frontend/src/views/GSecrets.vue:336]: ✅

File: frontend/src/views/GShootList.vue (hunk 3 above)
Comment (petersutter) [reply frontend/src/views/GShootList.vue]: ✅  as discussed

**Review by holgerkoser — APPROVED** [review]
/lgtm
