### PR TITLE
Ticket usability improvements

### LINKED ISSUE #824: UI issues of ticket feature
**What happened**:
Screenshot 2020-10-07 at 17 41 05

- line height of the title is wrong
- avatar is not loading when using enterprise github instance
- layout is broken
- code block exceeds parent container

**What you expected to happen**:
Screenshot 2020-10-08 at 11 31 23

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
This PR fixes several issues with the ticket feature

- line height of the title is wrong
- avatar is not loading when using enterprise github instance
- layout is broken
- code block exceeds parent container

It introduces a setting to specify the avatar source to be either
- `github`(default) - uses the avatar_url to fetch the avatar from github. Fetching the avatar image from an enterprise github could fail in case an authentication is required. In this case, use either `gravatar` or `none`
- `gravatar` - uses logon name to fetch the avatar from gravatar
- `none` - no avatar is displayed

Example `values.yaml`:
```yaml
frontendConfig:
  ticket:
    avatarSource: gravatar
```

Gravatar:
Screenshot 2020-10-08 at 11 28 00

No avatar:
Screenshot 2020-10-08 at 11 30 32

Fixed UI issues:
Screenshot 2020-10-08 at 11 31 23

**Which issue(s) this PR fixes**:
Fixes #824 

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fixed some UI issues of the tickets feature
```

### CODE REVIEW

File: frontend/src/components/ShootTickets/TicketComment.vue [hunk 1]
```diff
@@ -69,32 +89,50 @@ export default {
...
   }
+
   .comment-body {
-    padding: 5px;
+    border: 0.5px solid$cyan-darken-2;
+
+    padding-left: 8px;
+    padding-right: 8px;
+    padding-top: 4px;
+    padding-bottom: 4px;
```
Comment (holgerkoser) [inline frontend/src/components/ShootTickets/TicketComment.vue:125]:
```suggestion
    padding: 4px 8px;
```

File: frontend/src/components/ShootTickets/TicketComment.vue [hunk 2]
```diff
@@ -69,32 +89,50 @@ export default {
...
-    background-color: #00acc1;
+    border-bottom: 0.5px solid$cyan-darken-2;
+    background-color:$cyan-darken-2;
     color: white;
-    font-weight: 400;
+
+    padding-left: 8px;
+    padding-right: 8px;
+    padding-top: 4px;
+    padding-bottom: 4px;
```
Comment (holgerkoser) [inline frontend/src/components/ShootTickets/TicketComment.vue:115]:
```suggestion
    padding: 4px 8px;
```

File: frontend/src/components/ShootTickets/TicketComment.vue [hunk 3]
```diff
@@ -69,32 +89,50 @@ export default {
...
   }
+
   .comment-header {
     border-top-left-radius: 2px;
     border-top-right-radius: 2px;
     border: 0.5px;
-    padding: 5px;
-    border-bottom: 0.5px solid #00acc1;
-    background-color: #00acc1;
+    border-bottom: 0.5px solid$cyan-darken-2;
```
Comment (holgerkoser) [inline frontend/src/components/ShootTickets/TicketComment.vue:108]:
```suggestion
    border-bottom: 0.5px solid $cyan-darken-2;
```

File: frontend/src/components/ShootTickets/TicketComment.vue [hunk 4]
```diff
@@ -69,32 +89,50 @@ export default {
...
+    background-color:$cyan-darken-2;
```
Comment (holgerkoser) [inline frontend/src/components/ShootTickets/TicketComment.vue:109]:
```suggestion
    background-color: $cyan-darken-2;
```

File: frontend/src/components/ShootTickets/TicketComment.vue [hunk 5]
```diff
@@ -69,32 +89,50 @@ export default {
 </script>
 
 <style lang="scss" scoped>
+  @import '~vuetify/src/styles/styles.sass';
+
+  $cyan-darken-2: map-get($cyan, 'darken-1');
```
Comment (holgerkoser) [inline frontend/src/components/ShootTickets/TicketComment.vue:94]:
```suggestion
  $cyan-darken-1: map-get($cyan, 'darken-1');
```

**Review by holgerkoser — APPROVED** [review]
may be only cosmetic changes but all in all it 
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm
