### PR TITLE
Handling for duplicate worker zones

### LINKED ISSUE #812: Worker group update fails when user specifies duplicating zones
**What happened**:

User tries to change the image version of a worker group. The following error occurred:

> admission webhook "validation.aws.provider.extensions.gardener.cloud" denied the request: networks.zones: Forbidden: removing zones is not allowed 

**What you expected to happen**:

Worker is changed.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with a specific worker - it contains 3 availability zones from which 2 are the same:

```yaml
workers:
- name: cpu-worker
  machine:
    type: m5.4xlarge
    image:
      name: gardenlinux
      version: 27.0.1
  maximum: 3
  minimum: 3
  maxSurge: 1
  maxUnavailable: 0
  volume:
    type: gp2
    size: 200Gi
  zones:
    - ap-northeast-1a
    - ap-northeast-1c
    - ap-northeast-1c
```

and try to change the image in the dashboard.

**Anything else we need to know**:

The operation succeeds with the YAML editor. I would guess that the dashboard tries to remove the duplicating zone when doing the Patch operation and it ends up with:

```yaml
  zones:
    - ap-northeast-1a
    - ap-northeast-1c
```

which fails.

**Environment**:

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:
This PR adds handling for cases where a user defines the same zone multiple times for a worker group.

**Which issue(s) this PR fixes**:
Fixes #812

**Special notes for your reviewer**:

**Release note**:

```improvement user
In case a zone is defined multiple times for a worker group, the Dashboard is now able to handle this correctly
```

### CODE REVIEW

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 1]
```diff
@@ -314,15 +316,50 @@ export default {
...
+      const duplicateZones = filter(this.selectedZones, { isDuplicate: true })
+      const duplicateZoneItems = map(duplicateZones, duplicateZone => ({
+        text: duplicateZone.zone,
+        value: duplicateZone,
+        disabled: true
+      }))
+      return [...zoneItems, ...duplicateZoneItems]
     },
     zoneHint () {
+      console.log(this.maxAdditionalZones, this.availableZones.length)
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:359]:
```suggestion
```

File: frontend/src/utils/index.js [hunk 2]
```diff
@@ -42,6 +42,7 @@ import last from 'lodash/last'
 import sample from 'lodash/sample'
 import compact from 'lodash/compact'
 import store from '../store'
+import { sortBy } from 'lodash'
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:45]:
```suggestion
import sortBy from 'lodash/sortBy'
```

Comment (holgerkoser) [reply frontend/src/utils/index.js:45]: This breaks webpack tree shaking https://www.azavea.com/blog/2019/03/07/lessons-on-tree-shaking-lodash/

File: frontend/src/components/ShootWorkers/ManageWorkers.vue [hunk 3]
```diff
@@ -146,8 +152,7 @@ export default {
       if (!clusterRequiresZoneNetworkConfiguration) {
         return -1 // not applicable - no limit
       }
-      const totalNumberOfPossibleNetworkConfigurations = this.currentZonesWithNetworkConfigInShoot.length + this.currentFreeNetworks.length
-      if (totalNumberOfPossibleNetworkConfigurations >= this.allZones.length) {
+      if (this.currentFreeNetworks.length >= this.unusedZones.length) {
         return -1 // enough free networks - no limit
       }
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/ManageWorkers.vue:157]: maybe something like to get rid of the comment and magic number
```js
const NO_LIMIT = -1

export default {
...

  const hasFreeNetworks = this.currentFreeNetworks.length >= this.unusedZones.length
  if (hasFreeNetworks) {
    return NO_LIMIT
  }
```

File: frontend/src/utils/index.js [hunk 4]
```diff
@@ -777,6 +778,44 @@ export function expiringWorkerGroupsForShoot (shootWorkerGroups, shootCloudProfi
   })
 }
 
+export function convertDuplicateSelectedItemsToPlaceholders (items, sort = true, valuePropertyName) {
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:781]: The optional parameter should be last. Otherwise the default makes not much sense.

Comment (petersutter) [inline frontend/src/utils/index.js:781]: maybe introduce a class to have a frame around the two helper functions and to make it more readable?

class DuplicateSelectedItemsHelper

function itemsToPlaceholders
function placeholdersToItems

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 5]
```diff
@@ -314,15 +314,27 @@ export default {
         }
       }
     },
+    selectedZones: {
+      get: function () {
+        return ensureUniqueSelectedItemValues(this.worker.zones)
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:319]: How can we have duplicate selected items?

Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:319]: because of some shady yaml hackers ->discussed offline

File: frontend/src/utils/index.js (hunk 4 above)
Comment (grolu) [reply frontend/src/utils/index.js]: I reworked the whole code, please have a look. It might be still an option to move this into a class, but as we (currently) do not store property data, this might be over engineered. The data is held by the component that owns it and only uses the functions to convert between wrapped and non-wrapped format.

File: frontend/src/components/ShootWorkers/ManageWorkers.vue (hunk 3 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/ManageWorkers.vue:157]: done

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 6]
```diff
@@ -314,15 +314,28 @@ export default {
         }
       }
     },
+    selectedZones: {
+      get: function () {
+        return wrappedItemsForSelectedUnwrappedItems(this.zoneItems, this.worker.zones)
+      },
+      set: function (zoneValues) {
+        this.worker.zones = unwrapItemsByValues(this.zoneItems, zoneValues)
+        console.log(unwrapItemsByValues(this.zoneItems, zoneValues))
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:323]:
```suggestion
        this.worker.zones = unwrapItemsByValues(this.zoneItems, zoneValues)
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 7]
```diff
@@ -314,15 +314,28 @@ export default {
         }
       }
     },
+    selectedZones: {
+      get: function () {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:318]:
```suggestion
      get () {
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 8]
```diff
@@ -314,15 +314,28 @@ export default {
...
+        return wrappedItemsForSelectedUnwrappedItems(this.zoneItems, this.worker.zones)
+      },
+      set: function (zoneValues) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:321]:
```suggestion
      set (zoneValues) {
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 9]
```diff
@@ -314,15 +314,28 @@ export default {
...
+        this.worker.zones = unwrapItemsByValues(this.zoneItems, zoneValues)
+        console.log(unwrapItemsByValues(this.zoneItems, zoneValues))
+      }
+    },
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:325]:
```suggestion
    selectedZones: {
      get () {
        return map(this.worker.zones, (zone, index) => {
          return {
            value: [index, zone],
            text: zone,
            disabled: includes(this.immutableZones, zone)
          }
        })
      },
      set (zoneValues) {
        this.worker.zones = map(zoneValues, value => last(value))
      }
    },
    unselectedZones () {
      const unselectedZones = difference(this.allZones, this.worker.zones)
      return map(unselectedZones, (zone, index) => {
        return {
          value: [index, zone],
          text: zone,
          disabled: !includes(this.availableZones, zone)
        }
      })
    },
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 10]
```diff
@@ -314,15 +314,28 @@ export default {
...
-        text: zone,
-        value: zone,
-        disabled: includes(this.immutableZones, zone) || !includes(this.availableZones, zone)
+      const allWrappedZones = uniqueWrappersForItems(this.allZones, this.worker.zones)
+      const zoneItems = map(allWrappedZones, wrappedZone => ({
+        ...wrappedZone,
+        text: wrappedZone.item,
+        disabled: includes(this.immutableZones, wrappedZone.item) || !includes(this.availableZones, wrappedZone.item)
       }))
+      return sortBy(zoneItems, 'text')
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:333]:
```suggestion
      return sortBy(concat(this.selectedZones, this.unselectedZones), 'text')
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 11]
```diff
@@ -314,15 +314,28 @@ export default {
...
-      const sortedZones = sortBy(this.allZones)
-      return map(sortedZones, zone => ({
-        text: zone,
-        value: zone,
-        disabled: includes(this.immutableZones, zone) || !includes(this.availableZones, zone)
+      const allWrappedZones = uniqueWrappersForItems(this.allZones, this.worker.zones)
+      const zoneItems = map(allWrappedZones, wrappedZone => ({
+        ...wrappedZone,
+        text: wrappedZone.item,
+        disabled: includes(this.immutableZones, wrappedZone.item) || !includes(this.availableZones, wrappedZone.item)
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:331]:
```suggestion
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 12]
```diff
@@ -137,7 +137,7 @@ import map from 'lodash/map'
 import includes from 'lodash/includes'
 import sortBy from 'lodash/sortBy'
 import { required, maxLength, minValue, requiredIf } from 'vuelidate/lib/validators'
-import { getValidationErrors, parseSize } from '@/utils'
+import { getValidationErrors, parseSize, uniqueWrappersForItems, unwrapItemsByValues, wrappedItemsForSelectedUnwrappedItems } from '@/utils'
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:140]:
```suggestion
import { getValidationErrors, parseSize } from '@/utils'
```

File: frontend/src/utils/index.js [hunk 13]
```diff
@@ -777,6 +778,32 @@ export function expiringWorkerGroupsForShoot (shootWorkerGroups, shootCloudProfi
...
+    return get(find(allWrappedItems, { value }), 'item')
+  })
+}
+
+export function wrappedItemsForSelectedUnwrappedItems (wrappedItems, unwrappedItems) {
+  return map(unwrappedItems, (item, index) => {
+    return find(wrappedItems, { item, selectedArrayIndex: index })
+  })
+}
+
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:806]:
```suggestion
```

File: frontend/src/utils/index.js [hunk 14]
```diff
@@ -41,6 +41,7 @@ import join from 'lodash/join'
 import last from 'lodash/last'
 import sample from 'lodash/sample'
 import compact from 'lodash/compact'
+import difference from 'lodash/difference'
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:44]:
```suggestion
```

**Review by holgerkoser — APPROVED** [review]
/lgtm
