### PR TITLE
Do not modify theme objects returned from store

### LINKED ISSUE #1035: Do not mutate vuex store state outside mutation handlers
**What happened**:
Do not mutate the custom theme configuration.
https://github.com/gardener/dashboard/blob/master/frontend/src/store/index.js#L1311-L1315

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1035

**Special notes for your reviewer**:

**Release note**:

```bugfix user

```

### CODE REVIEW

File: frontend/src/store/index.js [hunk 1]
```diff
@@ -1546,7 +1546,7 @@ const actions = {
     const themes = get(Vue, 'vuetify.framework.theme.themes')
     if (themes) {
       const applyCustomThemeConfiguration = (name) => {
-        const customTheme = get(state, ['cfg', 'themes', name])
+        const customTheme = cloneDeep(get(state, ['cfg', 'themes', name]))
```
Comment (holgerkoser) [inline frontend/src/store/index.js:1549]: I think it would be better to directly update the vuetify theme without cloning and changing the configuration.
```js
  for (const name of ['light', 'dark']) {
    const theme = get(Vue.vuetify.framework.theme.themes, name)
    const themeConfiguration = get(state.cfg.themes, name)
    forOwn(themeConfiguration, (value, key) => {
      const color = get(colors, value)
      if (color) {
        theme[key] = color
      } else if (isHtmlColorCode(value)) {
        theme[key] = value
      }
    })
  }
```

Comment (grolu) [reply frontend/src/store/index.js]: ok

**Review by petersutter — APPROVED** [review]
/lgtm
