### PR TITLE
fix(frontend) performance issues in main menu project selection

### LINKED ISSUE #2701: Slow Gardener dashboard
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
Gardener dashboard became very slow since it displays additional information within the project drop down. It takes more than 20 seconds to update the UI in both Chrome and Firefox. We have more than 2000 projects, but with less projects it is also noticeable.

**What you expected to happen**:

UI should respond within a reasonable time.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: `1.132.2`
- Dashboard version: `1.82.5`

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2701

**Special notes for your reviewer**:

**Release note**:

```bugfix user
```

### CODE REVIEW

File: frontend/src/components/GMainNavigation.vue [hunk 1]
```diff
@@ -508,223 +194,29 @@ function getProjectMenuTargetRoute (namespace) {
...
-function onInputProjectFilter () {
-  highlightedProjectName.value = undefined
-  numberOfVisibleProjects.value = initialVisibleProjects
-
-  if (!projectNameThatMatchesFilter.value) {
-    return
-  }
+watch(selectedProject, project => {
+  const namespace = project?.spec?.namespace
+  if (!namespace) return
```
Comment (petersutter) [inline frontend/src/components/GMainNavigation.vue]: add brackets

File: frontend/src/components/GMainNavigation.vue [hunk 2]
```diff
@@ -508,223 +194,29 @@ function getProjectMenuTargetRoute (namespace) {
...
-}
+  const target = getProjectMenuTargetRoute(namespace)
 
-function highlightProjectWithKeys (keyDirection) {
-  const projectName = highlightedProjectName.value ?? selectedProjectName.value
+  const current = router.resolve(currentRoute)
+  const next = router.resolve(target)
 
-  let currentHighlightedIndex = findProjectIndexCaseInsensitive(projectName)
+  if (current.fullPath === next.fullPath) return
```
Comment (petersutter) [inline frontend/src/components/GMainNavigation.vue]: add brackets

File: frontend/src/components/GMainProjectSelection.vue [hunk 3]
```diff
@@ -0,0 +1,523 @@
...
+<template>
+  <v-menu
+    v-model="projectMenu"
+    location="bottom"
+    :attach="false"
+    open-on-click
+    :close-on-content-click="false"
+    :offset="[0]"
+    content-class="project-menu"
+    transition="slide-y-transition"
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue]: do we need this?

File: frontend/src/components/GMainProjectSelection.vue [hunk 4]
```diff
@@ -0,0 +1,523 @@
...
+    // reset index, regardless of key direction
+    currentHighlightedIndex = 0
+  } else if (keyDirection === 'up' && currentHighlightedIndex > 0) {
+    currentHighlightedIndex--
+  } else if (keyDirection === 'down' && currentHighlightedIndex < sortedAndFilteredProjectList.value.length - 1) {
+    currentHighlightedIndex++
+  }
+
+  const newHighlightedProject = sortedAndFilteredProjectList.value[currentHighlightedIndex] // eslint-disable-line security/detect-object-injection
+  highlightedProjectName.value = newHighlightedProject.metadata.name
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue]: bug: type in filter value so that no projects will appear in list, like "foo", then use up / down key. This will result in the error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'metadata') GMainProjectSelection.vue:371:56
```

File: frontend/src/components/GMainProjectSelection.vue [hunk 5]
```diff
@@ -0,0 +1,553 @@
+<!--
+SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
+
+SPDX-License-Identifier: Apache-2.0
+-->
+
+<template>
+  <!-- use scroll-y-transition as an animation using resize causes issues with v-virtual-scroll -->
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue]:
```suggestion
  <!-- scroll-y-transition used here - resize transitions cause issues with v-virtual-scroll (e.g., wrong initial scroll position or jumps after a delay) -->
```

File: frontend/src/components/GMainProjectSelection.vue [hunk 6]
```diff
@@ -0,0 +1,553 @@
...
+  <v-menu
+    v-model="projectMenu"
+    location="bottom"
+    :attach="false"
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue]:
```suggestion
```

File: frontend/src/components/GProjectTooltip.vue [hunk 7]
```diff
@@ -75,7 +75,7 @@ import { useProjectMetadata } from '@/composables/useProjectMetadata'
 import { useProvideProjectItem } from '@/composables/useProjectItem.js'
 
 const props = defineProps({
-  project: { type: Object, required: true },
```
Comment (petersutter) [inline frontend/src/components/GProjectTooltip.vue:78]: reset change?

File: frontend/src/components/GMainProjectSelection.vue [hunk 8]
```diff
@@ -0,0 +1,553 @@
...
+  if (targetIndex < 0) {
+    // reset index, regardless of key direction
+    targetIndex = 0
+  } else if (keyDirection === 'up' && currentHighlightedIndex > 0) {
+    targetIndex--
+  } else if (keyDirection === 'down' && currentHighlightedIndex < sortedAndFilteredProjectItems.value.length - 1) {
+    targetIndex++
+  }
+
+  const newHighlightedProject = sortedAndFilteredProjectItems.value[targetIndex] // eslint-disable-line security/detect-object-injection
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue]: provide reason for eslint-disable-line

File: frontend/src/components/GMainProjectSelection.vue [hunk 9]
```diff
@@ -0,0 +1,553 @@
...
+
+function isAllProjectsItem (project) {
+  return project?.spec.namespace === allProjectsItem.spec.namespace
+}
+
+onMounted(() => {
+  if (mdAndDown.value) {
+    sidebar.value = false
+  }
+})
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue]: remove sidebar logic from project selection

File: frontend/src/components/GMainProjectSelection.vue [hunk 10]
```diff
@@ -0,0 +1,553 @@
...
+      .project-name {
+        font-size: 14px;
+      }
+
+      .project-title, .project-owner {
+        font-size: 11px;
+      }
+
+      .project-tile-prepend-bar {
+        width: 4px;
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue:523]: with 4px border-radius all around?

File: frontend/src/components/GMainProjectSelection.vue [hunk 11]
```diff
@@ -0,0 +1,553 @@
...
+)
+
+async function scrollToActiveProject () {
+  const activeProjectName = highlightedProjectName.value ?? selectedProject.value?.metadata.name
+  if (!activeProjectName || !refProjectVirtualScroll.value) {
+    return
+  }
+
+  let index = findProjectIndexCaseInsensitive(activeProjectName)
+  index = index - 1 // padding
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue]: what is this padding about?

File: frontend/src/components/GMainProjectSelection.vue [hunk 12]
```diff
@@ -0,0 +1,553 @@
...
+            disabled: canCreateProject
+          }"
+          style="width: 100%"
+        >
+          <v-btn
+            variant="text"
+            block
+            class="project-add text-left text-primary"
+            :disabled="!canCreateProject"
+            @click.stop="openProjectDialog"
```
Comment (petersutter) [inline frontend/src/components/GMainProjectSelection.vue:173]: bug: create project dialog does not open

**Review by petersutter — APPROVED** [review]
/lgtm
