### PR TITLE
Fix console error when navigating to All Projects page

### LINKED ISSUE #1528: Console error when navigating to All Projects page
**What happened**:
The following error can be reproduced when you are either on the `Members` or on the `Administration` page and then navigate to the `All Projects` page.

Error when starting on `Secrets` page
```
index.js:332 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at getProjectDetails (index.js:332:31)
    at ReactiveEffect.fn (GMembers.vue:400:10)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at ReactiveEffect.fn (GMembers.vue:404:25)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at isOwner (GMembers.vue:591:16)
    at GMembers.vue:427:16
    at arrayMap (_arrayMap.js:16:21)
```
https://github.com/gardener/dashboard/blob/5895c5a442c4da5d25ac645b36c5ad3aee70074e/frontend/src/views/GMembers.vue#L399-L401

Error when starting on `Administration` page
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at getProjectDetails (index.js:332:31)
    at Proxy.projectDetails (GAdministration.vue:597:14)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at Object.get [as projectDetails] (runtime-core.esm-bundler.js:3407:22)
    at Object.get (runtime-core.esm-bundler.js:2912:20)
    at Proxy.staleSinceTimestamp (GAdministration.vue:666:19)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at Object.get [as staleSinceTimestamp] (runtime-core.esm-bundler.js:3407:22)
``` 
https://github.com/gardener/dashboard/blob/5895c5a442c4da5d25ac645b36c5ad3aee70074e/frontend/src/views/GAdministration.vue#L596-L598

https://github.com/gardener/dashboard/blob/5895c5a442c4da5d25ac645b36c5ad3aee70074e/frontend/src/utils/index.js#L331-L359

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
Previously, the getter made sure that always an object is returned https://github.com/gardener/dashboard/blob/e9d0d79776bd89a613fb2f7d7e599d2e7990c378/frontend/src/store/index.js#L598C49-L598C54
However I changed the utils function to default the project
I also removed deprecated computed properties

**Which issue(s) this PR fixes**:
Fixes #1528

**Special notes for your reviewer**:

**Release note**:

```bugfix user

```

### CODE REVIEW

**Review by grolu — APPROVED** [review]
/lgtm

File: frontend/src/components/ShootDetails/GGardenctlCommands.vue [hunk 1]
```diff
@@ -91,10 +91,10 @@ export default {
       'isAdmin',
     ]),
     ...mapState(useProjectStore, [
-      'projectFromProjectList',
+      'project',
```
Comment (holgerkoser) [inline frontend/src/components/ShootDetails/GGardenctlCommands.vue:94]: map `projectName`

**Review by holgerkoser — COMMENTED** [review]
We could directly map the projectName in this on case

File: frontend/src/components/ShootDetails/GGardenctlCommands.vue (hunk 1 above)
Comment (petersutter) [reply frontend/src/components/ShootDetails/GGardenctlCommands.vue]: ✅

File: frontend/src/components/ShootDetails/GGardenctlCommands.vue [hunk 2]
```diff
@@ -91,12 +91,8 @@ export default {
       'isAdmin',
     ]),
     ...mapState(useProjectStore, [
-      'projectFromProjectList',
+      'projectName',
```
[the remark this answers is not in the document]
Comment (petersutter) [reply frontend/src/components/ShootDetails/GGardenctlCommands.vue:92]: oh, right. fixed :check:

**Review by holgerkoser — APPROVED** [review]
/lgtm
