### PR TITLE
Remove grantType `authcode-keyboard`, add `device-code`

### LINKED ISSUE #1511: Remove Grant Type `authcode-keyboard` from dashboard frontent
**What happened**:
The Grant type `authcode-keyboard` is not suppoerted by SAP ID service and also [Google](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration) is stopping the support. It should be removed by default and may be enabled by configuration. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
The Grant type `authcode-keyboard` is not supported by SAP ID service and also [Google](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration) is stopping the support. It is removed by default but can enabled by configuration.
In addition, `device-code` grant type was added.
This applies for the garden cluster kubeconfig that can be downloaded on the `My Account` page.

Grant Types

The new default is:
```yaml
# charts/gardener-dashboard/values.yaml
global:
  dashboard:
    frontendConfig:
      grantTypes:
      - auto
      - authcode
      - device-code
```

If you want to restore the old behavior, set
```yaml
# charts/gardener-dashboard/values.yaml
global:
  dashboard:
    frontendConfig:
      grantTypes:
      - auto
      - authcode
      - authcode-keyboard
```
**Which issue(s) this PR fixes**:
Fixes #1511

**Special notes for your reviewer**:

**Release note**:

```other operator
The default grant types for the garden cluster OIDC kubeconfig have changed to `auto`, `authcode` and `device-code`. `authcode-keyboard` was removed and `device-code` grant type was added. The default grant types can be overridden by setting `Values.global.dashboard.frontendConfig.grantTypes` in the `gardener-dashboard` helm chart.
```

### CODE REVIEW

File: frontend/src/store/config.js [hunk 1]
```diff
@@ -126,6 +126,10 @@ export const useConfigStore = defineStore('config', () => {
     return state.value?.features
   })
 
+  const grantTypes = computed(() => {
+    return state.value?.grantTypes || ['auto', 'authcode', 'device-code']
```
Comment (petersutter) [inline frontend/src/store/config.js:130]:
```suggestion
    return state.value?.grantTypes ?? ['auto', 'authcode', 'device-code']
```

File: frontend/src/views/GAccount.vue [hunk 2]
```diff
@@ -270,14 +273,23 @@ export default {
...
+    const configStore = useConfigStore()
+    const grantTypes = configStore.grantTypes
+
+    const grantType = ref(head(grantTypes))
+
+    return {
+      grantType,
+      grantTypes,
+    }
+  },
```
Comment (holgerkoser) [inline frontend/src/views/GAccount.vue:286]: Use `mapState` instead of setup. 
```
  computed: {
    ...
    ...mapState(useKubeconfigStore, [
      'kubeconfigData',
      'isKubeconfigEnabled',
    ]),
    ...mapState(useConfigStore, [
      'grantTypes',
    ]),
    ... 
},
```

**Review by holgerkoser — APPROVED** [review]
/lgtm

File: frontend/src/views/GAccount.vue (hunk 2 above)
Comment (petersutter) [reply frontend/src/views/GAccount.vue]: ✅
