### PR TITLE
Volume minimum size fixes / improvements

### LINKED ISSUE #1949: Wrong display of volume minSize in shoot creation
**What happened**:
We have created new volumeTypes in the gcp CloudProfile (hyperdisk-balanced, hyperdisk-extreme, hyperdisk-throughput):
```
- name: hyperdisk-balanced
    class: premium
    minSize: 4Gi
  - name: hyperdisk-extreme
    class: premium
    minSize: 64Gi
  - name: hyperdisk-throughput
    class: premium
    minSize: 2Ti
```
However the dashboard UI is not showing the correct minSize.
We see  2 issues:
- Instead of showing the correct minSize of 4Gi or 64Gi it's always showing `Minimum size is 20`
- For hyperdisk-throughput with minSize 2Ti it's not showing any error at all

**What you expected to happen**:
The UI shows the correct minSize if the input is too small

**How to reproduce it (as minimally and precisely as possible)**:
Create a gcp shoot with one of the three new volumeTypes hyperdisk-balanced, hyperdisk-extreme or hyperdisk-throughput

**Anything else we need to know**:

**Environment**:
dev

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:
- Fixed reactivity for volume minimum size hint
- Added support for other size suffixes

**Which issue(s) this PR fixes**:
Fixes #1949

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Fixed display issues with minimum volume size
```

### CODE REVIEW

File: frontend/src/utils/index.js [hunk 1]
```diff
@@ -43,11 +43,21 @@ import {
 } from '@/lodash'
 
 const serviceAccountRegex = /^system:serviceaccount:([^:]+):([^:]+)$/
-const sizeRegex = /^(\d+)Gi$/
 const emailRegex = /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
 const colorCodeRegex = /^#([a-f0-9]{6}|[a-f0-9]{3})$/i
 const magnitudeNumberSuffixRegex = /^(\d+(?:\.\d*)?)([kmbt]?)$/i
 const versionRegex = /^(\d+)(?:\.(\d+))?(?:\.(\d+))?(?:\.\d+)*([-+].+)?$/
+const sizeRegex = /^(\d+)([GMKTi]{1,2})$/
```
Comment (petersutter) [inline frontend/src/utils/index.js:50]: might be relevant for #2029?

**Review by holgerkoser — APPROVED** [review]
/lgtm
