### PR TITLE
Fix status title for "Reconciliation Deactivated"

### LINKED ISSUE #645: Ignored shoot is shown as hibernated
**What happened**:
A cluster is shown as "hibernated" even though it is not in hibernation but ignored.

Screen Shot 2020-03-24 at 15 38 32

**What you expected to happen**:
The cluster should be shown as "ignored" or "reconciliation disabled".

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster
2. Add annotation `shoot.gardener.cloud/ignore: "true"`
3. Check "Monitoring" section on the shoot overview page.

**Environment**:
Dashboard version 1.40.2

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
Fixed status title for "Reconciliation Deactivated"

**Which issue(s) this PR fixes**:
Fixes #645 

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fixed status title for shoots that have the `shoot.gardener.cloud/ignore` annotation
```

### CODE REVIEW

**Comment by petersutter** [comment]
cc @timuthy

File: frontend/src/components/ShootStatus.vue [hunk 1]
```diff
@@ -175,7 +175,7 @@ export default {
         statusTitle.push('Hibernated')
       }
       if (this.reconciliationDeactivated) {
-        statusTitle.push('Hibernated')
```
Comment (grolu) [inline frontend/src/components/ShootStatus.vue]: 💩
