### PR TITLE
Fix vendor icon size

### LINKED ISSUE #1521: Azure Icon has wrong size on create cluster card
**What happened**:
The azure icon appears too small.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by grolu**
use `height`, `width` instead of `maxHeight`, `maxWidth` to ensure correct vendor icon sizes

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1521

**Special notes for your reviewer**:

**Release note**:

```bugfix user

```

### CODE REVIEW

File: frontend/src/components/GVendorIcon.vue [hunk 1]
```diff
@@ -119,8 +119,8 @@ const mdiIcon = computed(() => {
 const iconStyle = computed(() => {
   const maxIconSize = props.size - 4
```
Comment (holgerkoser) [inline frontend/src/components/GVendorIcon.vue:120]: rename this also

File: frontend/src/components/GVendorIcon.vue [hunk 2]
```diff
@@ -119,8 +119,8 @@ const mdiIcon = computed(() => {
...
   return {
-    maxHeight: `${maxIconSize}px`,
-    maxWidth: `${maxIconSize}px`,
+    height: `${maxIconSize}px`,
+    width: `${maxIconSize}px`,
```
Comment (holgerkoser) [inline frontend/src/components/GVendorIcon.vue:123]:
```suggestion
    maxHeight: `${maxIconSize}px`,
    maxWidth: `${maxIconSize}px`,
    height: `${maxIconSize}px`,
    width: `${maxIconSize}px`,
```

**Review by holgerkoser — APPROVED** [review]
/lgtm
