### PR TITLE
Fixed secret handling for cases where secretBindingName != secretName

### LINKED ISSUE #701: Secret shown as 'currently unused' when there are Shoots using it
**What happened**:
Cloud provider Secret shown as 'currently unused' when there are Shoots using it. This happens when the SecretBinding `.metadata.name` != Secret `.metadata.name`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create `Secret`
```yaml
apiVersion: v1
data:
  accessKeyID: "accessKeyID"
  secretAccessKey: "secretAccessKey"
kind: Secret
metadata:
  name: shoot-aws-secret-bar
  namespace: garden-baz
type: Opaque
```

2. Create `SecretBinding`
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: shoot-aws-secret-foo
  namespace: garden-baz
  labels:
    cloudprofile.garden.sapcloud.io/name: aws
secretRef:
  name: shoot-aws-secret-bar
  namespace: garden-baz
```

3. Create `Shoot`
```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  name: test
  namespace: garden-baz
spec:
  # [...]
  secretBindingName: shoot-aws-secret-foo
```

4. Ensure that the `shoot-aws-secret-bar` Secret in the dashboard is shown as `shoot-aws-secret-bar (currently unused)`

**Anything else we need to know**:

**Environment**:
Dashboard version: `1.42.0-dev-22049d66`

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:
Secret Bindings where name is not equal to Secret name did not show correct number of used clusters. Furthermore these secrets did not open on navigation (even if own secrets).
Also, I fixed the delete secret dialog which showed up blank (without any message), probably we broke the dialog with the latest vuetify upgrade.

**Which issue(s) this PR fixes**:
Fixes #701 

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fixed: Some Secrets were shown as 'currently unused' even if used by clusters. This happened for Secrets where the Secret Binding name is different from the Secret name
```

### CODE REVIEW

File: frontend/src/components/dialogs/SecretDialogDelete.vue [hunk 1]
```diff
@@ -36,12 +36,8 @@ limitations under the License.
 
       <v-card-text>
         <v-container fluid>
-          <template v-slot:message>
-            <div>
-              Are you sure to delete the secret <span class="font-weight-bold">{{name}}</span>?<br/>
-              <span class="red--text font-weight-bold">The operation can not be undone.</span>
-            </div>
-          </template>
+          Are you sure to delete the secret <span class="font-weight-bold">{{name}}</span>?<br/>
```
Comment (petersutter) [inline frontend/src/components/dialogs/SecretDialogDelete.vue:39]: what happened to the `<template v-slot:message>`? It's not needed anymore?

Comment (grolu) [reply frontend/src/components/dialogs/SecretDialogDelete.vue:39]: I asked myself the same question. I don't know but the slot doesn't exist anymore. This was the reason why the text did not show up. I also deleted the div as it is not required, but the template slot thingy was the reason for the issue
