### PR TITLE
Enhance User Errors

### LINKED ISSUE #1144: Display failed shoot constraints
**What would you like to be added**:

In the shoot status, gardener already publishes the so called "constraints", e.g.
```yaml
status:
  constraints:
    - type: HibernationPossible
      status: 'False'
      lastTransitionTime: '2021-12-08T08:59:44Z'
      lastUpdateTime: '2021-12-08T02:56:17Z'
      reason: ProblematicWebhooks
      message: >-
        ValidatingWebhookConfiguration "opa-validating-webhook" is problematic:
        webhook "validating-webhook.openpolicyagent.org" with failurePolicy
        "Ignore" and 30s timeout might prevent worker nodes from properly
        joining the shoot cluster
    - type: MaintenancePreconditionsSatisfied
      status: 'False'
      lastTransitionTime: '2021-12-08T08:59:44Z'
      lastUpdateTime: '2021-12-08T02:56:17Z'
      reason: ProblematicWebhooks
      message: >-
        ValidatingWebhookConfiguration "opa-validating-webhook" is problematic:
        webhook "validating-webhook.openpolicyagent.org" with failurePolicy
        "Ignore" and 30s timeout might prevent worker nodes from properly
        joining the shoot cluster
```

Also see [documentation](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_status.md#constraints).

It would be good to prominently display failed constraints in the shoot's details page.

**Why is this needed**:

Often times problematic webhook configurations and similar might be the cause for other problems in the cluster (e.g. worker nodes not joining the cluster), that are visible in the dashboard e.g. in the health checks.
- When operators start investigating such issues, it would be helpful to make them aware early on about the failed constraints, because it might speed up the process of investigation.
- When users notice such issues, they might be able to help themselves already by looking at the failed constraint's messages.

/kind enhancement
/area ops-productivity

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:
This PR improves the visibility of errors caused by misconfigurations and other issues that can be solved by the user.
It also adds several additional hints in case of MaintenacePrecondition failure (misconfigured webhook) - which will hopefully make users aware that there are measures to take on their end.

- Failed MaintenacePrecondition constraint is now rendered as error (not warning)
- Constraints that have an error code (see also https://github.com/gardener/gardener/issues/5778) will now be added to the readiness chips with an user error icon and additional information on how to resolve the issue
- Improved User error text to make users aware that they need to take action and the issue can not be solved by the gardener operators
- 
Screen Shot 2022-04-12 at 13 35 26

Screen Shot 2022-04-12 at 13 35 37

Screen Shot 2022-04-12 at 13 35 55

**Which issue(s) this PR fixes**:
Fixes #1144

**Special notes for your reviewer**:

**Release note**:

```feature operator
Improved visibility of user errors
```

### CODE REVIEW

**Comment by grolu** [comment]
/hold
until https://github.com/gardener/gardener/issues/5778 is merged

File: frontend/src/components/StatusTags.vue [hunk 1]
```diff
@@ -31,16 +38,29 @@ export default {
...
+      const allErrorCodes = errorCodesFromArray(this.filteredConditions)
+      return objectsFromErrorCodes(allErrorCodes)
     }
   }
 }
 </script>
+
+<style lang="scss" scoped>
+
+  .wrap {
```
Comment (holgerkoser) [inline frontend/src/components/StatusTags.vue:62]:
```suggestion
  .wrap-text {
```
We should move this `main.scss` because we already have there `nowrap` and the same `.wrap-text` in at least 8 other compoments

File: frontend/src/utils/index.js [hunk 2]
```diff
@@ -459,6 +459,7 @@ export function transformHtml (html, transformToExternalLinks = true) {
     if (transformToExternalLinks) {
       linkElement.classList.add('text-decoration-none')
       linkElement.setAttribute('target', '_blank')
+      linkElement.setAttribute('rel', 'noopener')
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:462]: Why not?
```suggestion
      linkElement.setAttribute('rel', 'noreferrer')
```

Comment (holgerkoser) [inline frontend/src/utils/index.js:462]: Why not?
```suggestion
      linkElement.setAttribute('rel', 'noreferrer')
```

File: frontend/src/utils/errorCodes.js [hunk 3]
```diff
@@ -107,5 +99,11 @@ const errorCodes = {
     description: 'Error occurred due to dependent objects on the infrastructure level. The operation will be retried automatically.',
     temporaryError: true,
     userError: false
+  },
+  ERR_USER_WEBHOOK: {
+    shortDescription: 'Misconfigured Webhook',
+    description: transformHtml('A misconfigured webhook prevents Gardener from performing operations. Please resolve this as this can lead to required actions not beeing performed which will eventually turn the cluster into an error state. Find best practises <a href="https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#best-practices-and-warnings">here</a>.'),
```
[the remark this answers is not in the document]
Comment (holgerkoser) [reply frontend/src/utils/errorCodes.js:105]: We have the `VueUtils` plugin.

[the remark this answers is not in the document]
Comment (holgerkoser) [reply frontend/src/utils/errorCodes.js:105]: We have the `VueUtils` plugin.

[the remark this answers is not in the document]
Comment (holgerkoser) [reply frontend/src/utils/errorCodes.js:105]: I anyway do not understand how this html could be rendered correctly.

File: frontend/src/components/ShootMessageDetails.vue [hunk 4]
```diff
@@ -73,7 +73,9 @@ SPDX-License-Identifier: Apache-2.0
                 :icon="userError ? 'mdi-account-alert' : 'mdi-alert'"
```
Comment (grolu) [inline frontend/src/components/ShootMessageDetails.vue:73]: use type error

File: frontend/src/utils/index.js (hunk 2 above)
Comment (grolu) [reply frontend/src/utils/index.js:462]: do not change (now) as we use `noopener` everywhere

File: frontend/src/utils/errorCodes.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/utils/errorCodes.js:105]: changed as discussed

File: frontend/src/utils/index.js (hunk 2 above)
Comment (grolu) [reply frontend/src/utils/index.js:462]: do not change (now) as we use `noopener` everywhere

File: frontend/src/components/ShootMessageDetails.vue (hunk 4 above)
Comment (grolu) [reply frontend/src/components/ShootMessageDetails.vue:73]: done

File: frontend/src/components/StatusTags.vue (hunk 1 above)
Comment (grolu) [reply frontend/src/components/StatusTags.vue]: done

File: frontend/src/components/ShootDetails/ShootAccessCard.vue [hunk 5]
```diff
@@ -303,7 +303,7 @@ export default {
     overflow-x: auto;
   }
 
-  .wrap-text {
+  .wrap-code {
```
Comment (holgerkoser) [inline frontend/src/components/ShootDetails/ShootAccessCard.vue:306]: This change is not needed.

File: frontend/src/components/StatusTags.vue [hunk 6]
```diff
@@ -18,22 +18,25 @@ SPDX-License-Identifier: Apache-2.0
       </status-tag>
     </div>
     <template v-if="showStatusText">
-      <div v-for="({ description }) in errorCodeObjects" :key="description" class="mt-1">
-        <div class="font-weight-bold error--text wrap" v-html="description" />
+      <div v-for="({ description, hint }) in errorCodeObjects" :key="description" class="mt-1">
+        <div class="font-weight-bold error--text wrap-text" v-html="description" />
```
Comment (holgerkoser) [inline frontend/src/components/StatusTags.vue:22]: We still have `v-html`?

File: frontend/src/utils/errorCodes.js [hunk 7]
```diff
@@ -102,7 +101,11 @@ const errorCodes = {
   },
   ERR_PROBLEMATIC_WEBHOOK: {
     shortDescription: 'Misconfigured Webhook',
-    description: transformHtml('A misconfigured webhook prevents Gardener from performing operations. Please resolve this as this can lead to required actions not beeing performed which will eventually turn the cluster into an error state. Find best practises <a href="https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#best-practices-and-warnings">here</a>.'),
+    description: 'A misconfigured webhook prevents Gardener from performing operations. Please resolve this as this can lead to required actions not beeing performed which will eventually turn the cluster into an error state.',
+    hint: {
```
Comment (holgerkoser) [inline frontend/src/utils/errorCodes.js:105]: Sorry. I know I have proposed hint. But now that I see it I would prefer link.

File: frontend/src/views/Administration.vue [hunk 8]
```diff
@@ -557,7 +557,7 @@ export default {
       margin: 0px;
     }
   }
-  .wrap-text {
+  .wrap-title-text {
```
Comment (holgerkoser) [inline frontend/src/views/Administration.vue:560]: Same as above. Since the style is scoped do not rename.

File: frontend/src/components/ShootDetails/ShootAccessCard.vue (hunk 5 above)
Comment (grolu) [reply frontend/src/components/ShootDetails/ShootAccessCard.vue:306]: yes, I know. But I wanted to highlight that this is not only wrap text but has more css styles. But I will change it back to .wrap-text, no problem.

File: frontend/src/components/StatusTags.vue (hunk 6 above)
Comment (grolu) [reply frontend/src/components/StatusTags.vue:22]: IDK how this could happen I thought I removed it.

File: frontend/src/views/Administration.vue (hunk 8 above)
Comment (grolu) [reply frontend/src/views/Administration.vue:560]: same as my comment above. Will revert it.

File: frontend/src/components/ShootMessageDetails.vue [hunk 9]
```diff
@@ -68,13 +68,15 @@ SPDX-License-Identifier: Apache-2.0
...
+                v-for="({description, hint, userError, infraAccountError}) in lastErrorDescription.errorCodeObjects" :key="description"
+                type="error"
                 :icon="userError ? 'mdi-account-alert' : 'mdi-alert'"
                 :prominent="!!userError"
               >
-                <h4 v-if="userError">Action required</h4>
-                <span class="wrap">
+                <h3 v-if="userError">Your Action is required</h3>
+                <h4 class="wrap-text font-weight-bold">This error is flagged as user error which indicates that no Gardener operator action is required.
+                Please read the error message carefully and take action.</h4>
```
Comment (petersutter) [inline frontend/src/components/ShootMessageDetails.vue:78]: Screenshot 2022-05-09 at 17 26 39

> Please read the error message ..
> Please double-check the error message ..

I understand that the second message is coming from gardener, but it's duplicative in this case

File: frontend/src/store/index.js [hunk 10]
```diff
@@ -145,6 +145,16 @@ const state = {
...
+    },
+    MaintenancePreconditionsSatisfied: {
+      displayName: 'Maintenance Preconditions Satisfied',
+      shortName: 'M',
+      description: 'Indicates whether Gardener is able to perform required actions during maintenance. If you not resolve this issue your cluster will eventually turn into an error state.'
+    },
+    HibernationPossible: {
+      displayName: 'Hibernation Preconditions Satisfied',
+      shortName: 'H',
+      description: 'Indicates whether Gardener is able to hibernate this cluster. If you not resolve this issue your hibernation schedule may not have any effect.'
```
Comment (petersutter) [inline frontend/src/store/index.js:157]:
```suggestion
      description: 'Indicates whether Gardener is able to hibernate this cluster. If you do not resolve this issue your hibernation schedule may not have any effect.'
```

File: frontend/src/components/ShootStatus.vue [hunk 11]
```diff
@@ -43,8 +43,9 @@ SPDX-License-Identifier: Apache-2.0
         <span v-if="showStatusText" class="d-flex align-center ml-2">{{statusTitle}}</span>
       </div>
       <template v-if="showStatusText">
-        <div v-for="({ description }) in tooltip.errorCodeObjects" :key="description">
-          <div class="font-weight-bold error--text wrap">{{description}}</div>
+        <div v-for="({ description, link }) in tooltip.errorCodeObjects" :key="description">
+          <div class="font-weight-bold error--text wrap-text">{{description}}</div>
+          <div class="font-weight-bold" v-if="link"><external-link :url="link.url">{{link.text}}</external-link></div>
```
Comment (petersutter) [inline frontend/src/components/ShootStatus.vue:48]: Screenshot 2022-05-09 at 17 37 54
I completely overlooked the hint as I didn't saw it in relation to the error message. Maybe because it had no error color or maybe because it was in a newline? 

I also expected to see this hint within the popover but there was none
Screenshot 2022-05-09 at 17 42 57

File: frontend/src/components/ShootMessageDetails.vue (hunk 9 above)
Comment (grolu) [reply frontend/src/components/ShootMessageDetails.vue:78]: Yes, I understand your thoughts. However, for the other user errors there are completely different error messages and it is not duplicative. So I'm not sure what we should do here...

Comment (petersutter) [reply frontend/src/components/ShootMessageDetails.vue:78]: I guess we should update the message in gardener then

**Review by holgerkoser — APPROVED** [review]
/lgtm
