### PR TITLE
Allow to set volume size if storage type is not fixed

### LINKED ISSUE #799: Volume size is not configurable for cloudprofiles without volume types.
**What happened**:
I have tried to create a Shoot cluster via the Dashboard for a cloud provider that has no volume types in its cloudprofile. But volume size dialog is hidden 
image
However, this cloud provider do support configurable volume size and I can set it via the YAML editor
```yaml
...
    workers:
      - name: worker-e3q72
        machine:
          type: m1.smallhdd
          image:
            name: coreos
            version: 2512.3.0
        maximum: 2
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          size: 80Gi
...
```

**What you expected to happen**:
To be able to configure the volume size even when volume types are missing in the cloudprofile.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by grolu**
Show correct storage information in volume selection and worker group popover

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #799

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Fixed: Volume size for machine types with a storage type that is not `fixed` can now be specified
```
```bugfix user
Fixed: Machine type storage information (if present) is now correctly displayed during selection and worker group overview
```
```breaking operator
With this release, the Dashboard offers the option to customize the volume size for all machine types by default. If you want to prevent the user from overwriting this value, you need to specify `spec.machineTypes.storage.type: fixed` in your cloud profile for all machineTypes that shall not support a custom volume size
```

### CODE REVIEW

**Comment by grolu** [comment]
/cc @dkistner @MartinWeindel @mandelsoft @marwinski @MalteJ @donistz @vlerenc 
Please note that this change affects all infrastructures that do not use `volumeTypes` in the cloud profile: If a machineType does not have `spec.machineTypes.storage.type == fixed` defined in the cloud profile, then we allow to set a custom volume size.

File: frontend/src/utils/index.js [hunk 1]
```diff
@@ -571,22 +571,33 @@ export function generateWorker (availableZones, cloudProfileName, region) {
...
-      type: volumeType,
       size: defaultVolumeSize
     }
   }
-
   return worker
 }
 
+export function machineTypeHasStorageWithTypeFixed (machineType) {
+  return machineType && machineType.storage && machineType.storage.type === 'default'
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:598]:
```suggestion
  return get(machineType, 'storage.type') === 'default'
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 2]
```diff
@@ -76,9 +76,16 @@ export default {
           })
           if (machineType.storage) {
             description.push({
-              title: 'Volume Size',
-              value: `${machineType.storage.size}`
+              title: 'Volume Type',
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:79]: I do not really understand what has priority from looking at the code. I looks like that double Volume Type and Volume Size descriptions can occur. It would split this large function into many smaller function for each description type.

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 3]
```diff
@@ -92,15 +99,21 @@ export default {
...
             description: `(Class: ${volumeType.class})`
           })
-        } else {
+        } else if (this.workerGroup.volume.type) {
           description.push({
             title: 'Volume Type',
             value: this.workerGroup.volume.type
           })
         }
+        if (this.workerGroup.volume.size) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:111]: DRY for property access e.g.
```js
const { machine, volume, minimum, maximum, maxSurge, zones = [] } = this.workerGroup
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 4]
```diff
@@ -252,6 +249,17 @@ export default {
           required: requiredIf(function () {
             return this.zonedCluster
           })
+        },
+        volumeSizeInternal: {
+          minVolumeSize: function (value) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:254]:
```suggestion
          minVolumeSize (value) {
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue (hunk 2 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue:79]: This should not happen as there should always be either storage **or** volume type defined in the cloud profile. However, I will try to improve the code, make it more robust and readable.

File: frontend/src/components/ShootWorkers/WorkerGroup.vue (hunk 3 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue]: ok

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 5]
```diff
@@ -65,81 +67,112 @@ export default {
...
-              value: `${machineType.storage.size}`
-            })
-          }
-        } else {
-          description.push({
-            title: 'Machine Type',
-            value: this.workerGroup.machine.type
-          })
+      description.push(this.machineTpeDescription(machine, machineType))
+      description.push(this.volumeTpeDescription(machine, machineType, volume, volumeType))
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:77]: typo tpe -> type

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 6]
```diff
@@ -65,81 +67,112 @@ export default {
...
       }
-      if (this.workerGroup.volume) {
-        const volumeType = find(this.volumeTypes, { name: this.workerGroup.volume.type })
+      return {
+        title: 'Machine Type',
+        value: machine.type
+      }
+    },
+    volumeTpeDescription (machine, machineType, volume, volumeType) {
+      if (volume) {
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:118]: early exit 
```js
if (!volume) {
  return
}

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 7]
```diff
@@ -65,81 +67,112 @@ export default {
...
+          title: 'Volume Size',
+          value: `${storageSize}`
+        }
       }
-      if (this.workerGroup.zones) {
-        description.push({
-          title: this.workerGroup.zones.length > 1 ? 'Zones' : 'Zone',
-          value: join(this.workerGroup.zones, ', ')
-        })
+    },
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:157]: the machine parameter is not used
```js
    volumeSizeDescription (machineType, volume) {
      const storageSize = get(machineType, 'storage.size')
      const size = get(volume, 'size', storageSize)
      if (size) {
        return {
          title: 'Volume Size',
          value: `${size}`
        }
      }
    }
```

File: frontend/src/utils/index.js [hunk 8]
```diff
@@ -571,22 +571,33 @@ export function generateWorker (availableZones, cloudProfileName, region) {
...
     worker.volume = {
-      type: volumeType,
       size: defaultVolumeSize
     }
   }
-
   return worker
 }
 
+export function machineTypeHasStorageWithTypeFixed (machineType) {
```
Comment (petersutter) [inline frontend/src/utils/index.js:597]: better name maybe: isMachineTypeStorageFixed ?

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 9]
```diff
@@ -362,13 +396,20 @@ export default {
...
       this.validateInput()
     },
     onUpdateVolumeType () {
       this.validateInput()
     },
     onInputVolumeSize () {
-      this.$v.worker.volume.size.$touch()
+      const machineType = this.selectedMachineType
+      if (!this.canDefineVolumeSize || get(machineType, 'storage.size') === this.volumeSizeInternal) {
+        delete this.worker.volume
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:408]: don't understand

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 10]
```diff
@@ -264,14 +272,40 @@ export default {
     volumeInCloudProfile () {
       return !isEmpty(this.volumeTypes)
     },
+    selectedMachineType () {
+      return find(this.machineTypes, { name: this.worker.machine.type })
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:276]:
```suggestion
      return find(this.machineTypes, ['name', this.worker.machine.type])
```

File: frontend/src/utils/index.js (hunk 8 above)
Comment (holgerkoser) [reply frontend/src/utils/index.js:597]: Agree

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 11]
```diff
@@ -65,81 +67,112 @@ export default {
...
+    machineImageDescription (machine, machineImage) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:158]: What is the difference between `machine.image` and `machineImage`.

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 12]
```diff
@@ -65,81 +67,112 @@ export default {
...
+          description: `(Class: ${machineType.storage.class})`
         }
       }
-      if (this.workerGroup.minimum && this.workerGroup.maximum) {
-        description.push({
-          title: 'Autoscaler',
-          value: `Min. ${this.workerGroup.minimum} / Max. ${this.workerGroup.maximum}`
-        })
+    },
+    volumeSizeDescription (machine, machineType, volume) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:141]: I assume the leading information is the `volume` and the fallback is the machineType. Maybe even optional. This should be reflected in the function parameters

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 13]
```diff
@@ -65,81 +67,112 @@ export default {
...
+          title: zones.length > 1 ? 'Zones' : 'Zone',
+          value: join(zones, ', ')
+        })
+      }
+
+      return compact(description)
+    }
+  },
+  methods: {
+    machineTpeDescription (machine, machineType) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:104]: Methods should not have property names. Better `getMachineTypeDescription`

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 14]
```diff
@@ -65,81 +67,112 @@ export default {
       return this.machineImagesByCloudProfileName(this.cloudProfileName)
     },
     description () {
+      const { machine, volume, minimum, maximum, maxSurge, zones = [] } = this.workerGroup
+      const machineType = find(this.machineTypes, { name: machine.type })
+      const volumeType = find(this.volumeTypes, { name: get(volume, 'type') })
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:72]: Why using lodash for volume and not for machine?

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 15]
```diff
@@ -65,81 +67,112 @@ export default {
...
+      const machineImage = find(this.machineImages, machine.image)
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:73]:
```suggestion
      const { machine = {}, volume = {}, minimum, maximum, maxSurge, zones = [] } = this.workerGroup
      const machineType = find(this.machineTypes, ['name', machine.type])
      const volumeType = find(this.volumeTypes, ['name', volume.type'])
      const machineImage = find(this.machineImages, pick(machine.image, ['name', 'version']))
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 16]
```diff
@@ -65,81 +67,112 @@ export default {
...
         }
       }
-      if (this.workerGroup.volume) {
-        const volumeType = find(this.volumeTypes, { name: this.workerGroup.volume.type })
+      return {
+        title: 'Machine Type',
+        value: machine.type
+      }
+    },
+    volumeTpeDescription (machine, machineType, volume, volumeType) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:117]: These helper methods should look something like this:
```js
function getMachineTypeDescription (workerGroup, machineType) {
  const { machine = {} } = workerGroup
  const item = {
    title: 'Machine Type',
    value: machine.type
  }
  if (machineType) {
    const { cpu, gpu, memory } = machineType
    item.description = `(CPU: ${cpu} | GPU: ${gpu} | Memory: ${memory})`
  }
  return item
}
function getVolumeTypeDescription (workerGroup, volumeType, machineType) {
  const { volume = {} } = workerGroup
  if (!volume.type) {
    return
  }
  const item = {
    title: 'Volume Type',
    value: volume.type
  }
  const storageClass = get(volumeType, 'class', get(machineType, 'storage.class'))
  if (storageClass) {
    item.description = `(Class: ${storageClass})`
  }
  return item
}
function getVolumeSizeDescription (workerGroup, machineType) {
  const { volume = {} } = workerGroup
  const size = get(volume, 'size', get(machineType, 'storage.size'))
  if (!size) {
    return
  }
  return {
    title: 'Volume Size',
    value: `${size}`
  }
}
function getMachineImageDescription (workerGroup, machineImage) {
  const { machine: { image = {} } = {} } = workerGroup
  if (!image.name) {
    return
  }
  const item = {
    title: 'Machine Image',
    value: `${image.name} | Version: ${image.version}`
  }
  const expirationDate = get(machineImage, 'expirationDate')
  if (expirationDate) {
    item.description = `(Expires: ${machineImage.expirationDateString})`
  }
  return item
}
```

File: frontend/src/utils/index.js [hunk 17]
```diff
@@ -571,22 +571,33 @@ export function generateWorker (availableZones, cloudProfileName, region) {
...
+  if (volumeType.name) {
+    worker.volume = {
+      type: volumeType.name,
+      size: defaultVolumeSize
+    }
+  } else if (machineType.storage && !machineTypeHasStorageWithTypeFixed(machineType)) {
+    worker.volume = {
+      size: machineType.storage.size
+    }
+  } else if (!machineType.storage) {
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:589]: move this else if before `else if (machineType.storage && !machineTypeHasStorageWithTypeFixed(machineType)) `

File: frontend/src/utils/index.js (hunk 8 above)
Comment (holgerkoser) [reply frontend/src/utils/index.js:597]: We should change the helper method to `isMachineTypeStorageNotFixed` and also check machineType.store

File: frontend/src/components/ShootWorkers/WorkerGroup.vue (hunk 7 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue:157]: refactored method(s)

File: frontend/src/utils/index.js (hunk 8 above)
Comment (grolu) [reply frontend/src/utils/index.js:597]: renamed to `machineTypeHasStorageButNotWithTypeFixed`

Comment (grolu) [reply frontend/src/utils/index.js:597]: and added check for machineType.storage

File: frontend/src/components/ShootWorkers/WorkerGroup.vue (hunk 15 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue:73]: done

File: frontend/src/components/ShootWorkers/WorkerGroup.vue (hunk 16 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue:117]: done

Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue]: improved as suggested

File: frontend/src/utils/index.js (hunk 17 above)
Comment (grolu) [reply frontend/src/utils/index.js]: done

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue (hunk 9 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerInputGeneric.vue]: I added some comments to make it clearer

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 18]
```diff
@@ -66,81 +67,122 @@ export default {
...
+          title: zones.length > 1 ? 'Zones' : 'Zone',
+          value: join(zones, ', ')
         })
       }
+
       return description
     }
+  },
+  methods: {
+    getMachineTpeDescription () {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:105]:
```suggestion
    getMachineTypeDescription () {
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 19]
```diff
@@ -66,81 +67,122 @@ export default {
...
-            value: `${volumeType.name} / ${this.workerGroup.volume.size}`,
-            description: `(Class: ${volumeType.class})`
-          })
-        } else {
-          description.push({
-            title: 'Volume Type',
-            value: this.workerGroup.volume.type
-          })
-        }
+      description.push(this.getMachineTpeDescription())
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:70]:
```suggestion
      description.push(this.machineTypeDescription)
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 20]
```diff
@@ -66,81 +67,122 @@ export default {
...
+      const volumeTypeDescription = this.getVolumeTypeDescription()
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:71]:
```suggestion
      const volumeTypeDescription = this.volumeTypeDescription
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 21]
```diff
@@ -66,81 +67,122 @@ export default {
...
-            machineImageDescription.description = `(Expires: ${machineImage.expirationDateString})`
-          }
-          description.push(machineImageDescription)
-        } else {
-          description.push({
-            title: 'Machine Image',
-            value: this.workerGroup.machine.image
-          })
-        }
+      const volumeSizeDescription = this.getVolumeSizeDescription()
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:75]:
```suggestion
      const volumeSizeDescription = this.volumeSizeDescription
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 22]
```diff
@@ -66,81 +67,122 @@ export default {
...
+      if (volumeTypeDescription) {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:76]:
```suggestion
      if (volumeSizeDescription) {
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 23]
```diff
@@ -66,81 +67,122 @@ export default {
...
+        description.push(volumeSizeDescription)
       }
-      if (this.workerGroup.minimum && this.workerGroup.maximum) {
+      description.push(this.getMachineImageDescription())
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:79]:
```suggestion
      description.push(this.machineImageDescription)
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 24]
```diff
@@ -66,81 +67,122 @@ export default {
...
+
+      const machineImageMetadata = find(this.machineImages, { name, version })
+      if (!machineImageMetadata) {
+        item.description = '(Image is expired)'
+      } else if (machineImageMetadata.expirationDate) {
+        item.description = `(Expires: ${machineImageMetadata.expirationDateString})`
+      }
+
+      return item
+    }
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:185]:
```suggestion
    machineType () {
      const type = get(this.workerGroup, 'machine.type')
      return find(this.machineTypes, ['name', type])
    },
    volumeType () {
      const type = get(this.workerGroup, 'volume.type')
      return find(this.volumeTypes, ['name', type])
    },
    machineImage () {
      const { name, version } = get(this.workerGroup, 'machine.image', {})
      return find(this.machineImages, { name, version })
    },
    machineTypeDescription () {
      const machine = get(this.workerGroup, 'machine', {})
      const item = {
        title: 'Machine Type',
        value: machine.type
      }

      const machineType = this.machineType
      if (machineType) {
        const { cpu = '', gpu = '', memory = '' } = machineType
        item.description = `(CPU: ${cpu} | GPU: ${gpu} | Memory: ${memory})`
      }

      return item
    },
    volumeTypeDescription () {
      // workers with volume type (e.g. aws)
      const volume = get(this.workerGroup, 'volume', {})
      if (volume.type) {
        const item = {
          title: 'Volume Type',
          value: volume.type
        }

        const volumeType = this.volumeType
        if (volumeType) {
          item.description = `(Class: ${volumeType.class})`
        }

        return item
      }

      // workers with storage in machine type metadata (e.g. openstack)
      const storage = get(this.machineType, 'storage', {})
      if (storage.type) {
        return {
          title: 'Volume Type',
          value: storage.type,
          description: `(Class: ${storage.class})`
        }
      }
    },
    volumeSizeDescription () {
      // all infras support volume sizes, but for some they are optional
      const volume = get(this.workerGroup, 'volume', {})
      if (volume.size) {
        return {
          title: 'Volume Size',
          value: `${volume.size}`
        }
      }

      // if no size is defined on the worker itself, check if machine storage defines a default size
      const storage = get(this.machineType, 'storage', {})
      if (storage.size) {
        return {
          title: 'Volume Size',
          value: `${storage.size}`
        }
      }
    },
    machineImageDescription () {
      const { name, version }  = get(this.workerGroup, 'machine.image', {})
      const item = {
        title: 'Machine Image',
        value: `${name} | Version: ${version}`
      }

      const machineImage = this.machineImage
      if (!machineImage) {
        item.description = '(Image is expired)'
      } else if (machineImage.expirationDate) {
        item.description = `(Expires: ${machineImage.expirationDateString})`
      }

      return item
    }
```

File: frontend/src/utils/index.js [hunk 25]
```diff
@@ -571,22 +571,33 @@ export function generateWorker (availableZones, cloudProfileName, region) {
...
       size: defaultVolumeSize
     }
   }
-
   return worker
 }
 
+export function machineTypeHasStorageButNotWithTypeFixed (machineType) {
+  return machineType && machineType.storage && machineType.storage.type !== 'fixed'
+}
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:599]:
```suggestion
export function machineTypeHasStorageAndTypeNotFixed ({ storage } = {}) {
  return storage && storage.type !== 'fixed'
}
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 26]
```diff
@@ -264,14 +272,44 @@ export default {
...
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:276]:
```suggestion
      return find(this.machineTypes, ['name', this.worker.machine.type])
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue (hunk 24 above)
Comment (holgerkoser) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue:185]: If there is a machineImage but it has no expirationDate we do not show a description. Should it be (Image is up to date)?

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 27]
```diff
@@ -97,82 +98,90 @@ export default {
...
           title: 'Volume Type',
           value: storageType,
-          description: `(Class: ${machineType.storage.class})`
+          description: `(Class: ${machineMetadata.storage.class})`
         }
       }
     },
-    volumeSizeDescription (machine, machineType, volume) {
+    getVolumeSizeDescription () {
+      // all infras support volume sizes, but for some they are optional
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:149]:
```suggestion
      // all infrastructures support volume sizes, but for some they are optional
```

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 28]
```diff
@@ -56,27 +56,33 @@ export default {
...
+      const machineImages = this.machineImagesByCloudProfileName(this.cloudProfileName)
+      const { name, version } = get(this.workerGroup, 'machine.image', {})
+      return find(machineImages, { name, version })
     },
-    description () {
+    workerGroupDescriptions () {
       const description = []
-      description.push(this.getMachineTpeDescription())
-      const volumeTypeDescription = this.getVolumeTypeDescription()
+      description.push(this.machineTpeDescription)
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:76]: there is still a typo: tpe -> type

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 29]
```diff
@@ -55,91 +56,135 @@ export default {
...
-              value: `${machineType.storage.size}`
-            })
-          }
-        } else {
-          description.push({
-            title: 'Machine Type',
-            value: this.workerGroup.machine.type
-          })
-        }
+      description.push(this.machineTpeDescription)
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:76]:
```suggestion
      description.push(this.machineTypeDescription)
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 30]
```diff
@@ -264,14 +272,43 @@ export default {
...
+        return true
+      }
+      const storage = get(this.selectedMachineType, 'storage')
+      if (!storage.type) {
+        return true
+      }
+      if (storage.type !== 'fixed') {
+        return true
+      }
+      return false
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:292]:
```suggestion
      // user is allowed to set a volume size
      if (this.volumeInCloudProfile) {
        return true
      }
      return get(this.selectedMachineType, 'storage.type') !== 'fixed'
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 31]
```diff
@@ -273,21 +273,20 @@ export default {
...
-      if (machineTypeHasStorageButNotWithTypeFixed(machineType)) {
+      const storage = get(this.selectedMachineType, 'storage')
+      if (!storage.type) {
         return true
       }
-      if (machineType && !machineType.storage) {
+      if (storage.type !== 'fixed') {
         return true
       }
       return false
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue]: much better 👍

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 32]
```diff
@@ -264,14 +272,43 @@ export default {
...
+      const minimumVolumeSize = parseSize(this.minimumVolumeSizeByCloudProfileNameAndRegion({ cloudProfileName: this.cloudProfileName, region: this.region }))
+
+      const machineType = this.selectedMachineType
+      const machineTypeStorageSize = get(machineType, 'storage.size')
+      if (machineTypeStorageSize) {
+        const machineTypeDefaultSize = parseSize(machineTypeStorageSize)
+        if (machineTypeDefaultSize && machineTypeDefaultSize < minimumVolumeSize) {
+          return machineTypeDefaultSize
+        }
+      }
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:309]:
```suggestion
      const storageSize =  parseSize(get(this.selectedMachineType, 'storage.size'))
      if (storageSize > 0 && storageSize < minimumVolumeSize) {
        return storageSize
      }
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 33]
```diff
@@ -415,10 +464,31 @@ export default {
...
+    setVolumeDependingOnMachineType () {
+      const storage = get(this.selectedMachineType, 'storage')
+      if (!storage) {
+        return
+      }
+      // machine type has storage
+      if (get(this.worker, 'volume.size')) {
+        return
+      }
+      // volume sizen is not defined on worker (=default storage size)
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:477]:
```suggestion
      // volume size is not defined on worker (=default storage size)
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue (hunk 30 above)
Comment (petersutter) [reply frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:292]: even better 👍

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 34]
```diff
@@ -415,10 +464,31 @@ export default {
...
+        this.volumeSizeInternal = storage.size
+      }
     }
   },
   mounted () {
     this.validateInput()
+    const workerVolumeSize = get(this.worker, 'volume.size')
+    if (workerVolumeSize) {
+      this.volumeSizeInternal = workerVolumeSize
+    }
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:489]:
```suggestion
    const volumeSize = get(this.worker, 'volume.size')
    if (volumeSize) {
      this.volumeSizeInternal = volumeSize
    }
```

File: frontend/src/utils/index.js [hunk 35]
```diff
@@ -571,19 +571,26 @@ export function generateWorker (availableZones, cloudProfileName, region) {
...
     worker.volume = {
-      type: volumeType,
+      type: volumeType.name,
       size: defaultVolumeSize
     }
+  } else if (!machineType.storage) {
+    worker.volume = {
+      size: defaultVolumeSize
+    }
+  } else if (get(machineType, 'storage.size') !== 'fixed') {
```
Comment (holgerkoser) [inline frontend/src/utils/index.js:589]:
```suggestion
  } else if (get(machineType, 'storage.type') !== 'fixed') {
```

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue (hunk 32 above)
Comment (petersutter) [reply frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:309]: this could potentially lead to a console.error log, or not?

File: frontend/src/components/ShootWorkers/WorkerGroup.vue (hunk 28 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue:76]: done

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 36]
```diff
@@ -55,91 +56,135 @@ export default {
...
-          title: this.workerGroup.zones.length > 1 ? 'Zones' : 'Zone',
-          value: join(this.workerGroup.zones, ', ')
+          title: zones.length > 1 ? 'Zones' : 'Zone',
+          value: join(zones, ', ')
         })
       }
+
       return description
+    },
+    machineTpeDescription () {
```
[the remark this answers is not in the document]
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue:109]: done

File: frontend/src/components/ShootWorkers/WorkerGroup.vue (hunk 29 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerGroup.vue:76]: done

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue (hunk 32 above)
Comment (grolu) [reply frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:302]: will double check

File: frontend/src/components/ShootWorkers/WorkerInputGeneric.vue [hunk 37]
```diff
@@ -264,14 +272,32 @@ export default {
...
       return filter(this.machineImagesByCloudProfileName(this.cloudProfileName), ({ isExpired }) => {
         return !isExpired
       })
     },
     minimumVolumeSize () {
-      const minimumVolumeSize = this.minimumVolumeSizeByCloudProfileNameAndRegion({ cloudProfileName: this.cloudProfileName, region: this.region })
-      return parseSize(minimumVolumeSize)
+      const minimumVolumeSize = parseSize(this.minimumVolumeSizeByCloudProfileNameAndRegion({ cloudProfileName: this.cloudProfileName, region: this.region }))
+
+      const defaultSize =  parseSize(get(this.selectedMachineType, 'storage.size'))
```
Comment (petersutter) [inline frontend/src/components/ShootWorkers/WorkerInputGeneric.vue:295]:
```suggestion
      const defaultSize = parseSize(get(this.selectedMachineType, 'storage.size'))
```

**Review by petersutter — APPROVED** [review]
/lgtm apart from lint error

**Review by holgerkoser — APPROVED** [review]
/lgtm

File: frontend/src/components/ShootWorkers/WorkerGroup.vue [hunk 38]
```diff
@@ -55,91 +56,135 @@ export default {
...
     },
-    machineImages () {
-      return this.machineImagesByCloudProfileName(this.cloudProfileName)
+    machineImage () {
+      const machineImages = this.machineImagesByCloudProfileName(this.cloudProfileName)
+      const { name, version } = get(this.workerGroup, 'machine.image', {})
+      return find(machineImages, { name, version })
     },
-    description () {
+    workerGroupDescriptions () {
```
Comment (holgerkoser) [inline frontend/src/components/ShootWorkers/WorkerGroup.vue:74]: Why `workerGroupDescriptions` and not just `descriptions`? The name of the component is `WorkerGroup`!
