### PR TITLE
Hide retry button as viewer

### LINKED ISSUE #2477: Retry button visible as viewer
**What happened**:
The retry button should not be visible to users with only viewer permission, as otherwise they run into a permission error when clicking on it.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by klocke-io**
**What this PR does / why we need it**:
Retry button was visible as viewer
**Which issue(s) this PR fixes**:
Fixes #2477

**Special notes for your reviewer**:

**Release note**:

```bugfix user

```

### CODE REVIEW

**Review by grolu — APPROVED** [review]
Remove comment in if stmt
Otherwise /lgtm

File: frontend/src/components/GRetryOperation.vue [hunk 1]
```diff
@@ -52,7 +54,14 @@ const appStore = useAppStore()
 
 const retryingOperation = ref(false)
 
+const authzStore = useAuthzStore()
+const {
+  canPatchShoots,
+} = storeToRefs(authzStore)
+
 const canRetry = computed(() => {
+  if (!canPatchShoots.value) return // No permission to patch shoots
```
Comment (petersutter) [inline frontend/src/components/GRetryOperation.vue]: the comment is unnecessary, also we always add brackets (should have a linter for it). I also returned false to make it more explicit
```suggestion
  if (!canPatchShoots.value) {
    return false
  }
```
